// sidecoach/scripts/generate-validators.ts
//
// THIN wrapper: all pure logic lives in ../src/validator-generation (inside
// rootDir ./src so the test imports it without TS6059). This file only does file
// I/O + --check. Re-exports the pure fns for back-compat (mirrors how
// generate-lanes.ts re-exports lane-derivation).
import * as fs from 'fs';
import * as path from 'path';
import { RULES } from '../src/product-rule-registry';
import { VALIDATOR_REGISTRATIONS, LANE_POLICIES, FIXTURE_MANIFEST } from '../src/flow-validation-capabilities';
import {
  deriveValidator, validateRegistry, validateFixtureManifest, gatingValidatorIds, deriveFlowCapabilities,
  BROWSER_BACKED_RULE_IDS, RENDERED_BACKED_RULE_IDS,
} from '../src/validator-generation';

export {
  deriveValidator, validateRegistry, validateFixtureManifest, gatingValidatorIds, deriveFlowCapabilities,
} from '../src/validator-generation';

const SC = path.resolve(__dirname, '..');
const OUT = path.resolve(SC, 'src', 'validators.generated.ts');

function render(): string {
  const validators = VALIDATOR_REGISTRATIONS.map((reg) => deriveValidator(reg, RULES));
  const flows = deriveFlowCapabilities();
  return (
    `// GENERATED by sidecoach/scripts/generate-validators.ts - DO NOT EDIT BY HAND.\n` +
    `// Source: product-rule-registry.ts + flow-validation-capabilities.ts\n` +
    `import type { CleanPolicy, SourceKindSupport } from './product-rule-types';\n\n` +
    `export interface GeneratedValidator { validatorId: string; ownedRuleIds: string[]; registryScope: string[]; supportedSourceKinds: SourceKindSupport[]; browserRuleIds: string[]; browserCoverageByScope: import('./product-rule-types').RequiredCoverageRecord[]; renderedRuleIds: string[]; renderedCoverageByScope: import('./product-rule-types').RequiredCoverageRecord[]; cleanPolicy: CleanPolicy; }\n` +
    `export interface GeneratedFlowCapability { flowId: string; capability: 'product_validator' | 'advisory' | 'none'; }\n\n` +
    `export const GENERATED_VALIDATORS: GeneratedValidator[] = ${JSON.stringify(validators, null, 2)};\n\n` +
    `export const GENERATED_FLOW_CAPABILITIES: GeneratedFlowCapability[] = ${JSON.stringify(flows, null, 2)};\n`
  );
}

function main() {
  const check = process.argv.includes('--check');
  const errors = [
    ...validateRegistry(RULES, VALIDATOR_REGISTRATIONS, gatingValidatorIds(LANE_POLICIES), [...BROWSER_BACKED_RULE_IDS], [...RENDERED_BACKED_RULE_IDS]).errors,
    ...validateFixtureManifest(gatingValidatorIds(LANE_POLICIES), FIXTURE_MANIFEST).errors,
  ];
  if (errors.length) { console.error('generate-validators: INVALID registry/manifest\n' + errors.map((e) => '  - ' + e).join('\n')); process.exit(1); }
  const want = render();
  if (check) {
    const have = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf-8') : '';
    if (have !== want) { console.error(`generate-validators --check: DRIFT in ${path.relative(SC, OUT)}`); process.exit(1); }
    console.log('generate-validators --check: OK (registry valid, manifest present, no drift)');
    return;
  }
  fs.writeFileSync(OUT, want);
  console.log(`generate-validators: wrote ${path.relative(SC, OUT)}`);
}

if (require.main === module) main();
