import * as fs from 'fs';
import * as path from 'path';
import { deriveFlowSequence, deriveVerbGuidance, deriveVerbSteps } from '../src/lane-derivation';

const ROOT = path.resolve(__dirname, '..', '..');
const JSON_PATH = path.join(ROOT, 'claude', 'hooks', 'sidecoach-lanes.json');
const TS_OUT = path.resolve(__dirname, '..', 'src', 'lanes.generated.ts');
const MD_OUT = path.resolve(__dirname, '..', 'LANES.generated.md');

// deriveFlowSequence / deriveVerbGuidance live in ../src/lane-derivation so the
// derivation test can import them without a src/ -> scripts/ rootDir crossing
// (TS6059). Re-exported here so consumers importing from the generator still work.
export { deriveFlowSequence, deriveVerbGuidance, deriveVerbSteps } from '../src/lane-derivation';

function buildModel() {
  const reg = JSON.parse(fs.readFileSync(JSON_PATH, 'utf-8'));
  return reg.lanes.map((l: any) => {
    const flowSequence = deriveFlowSequence(l.verbChain);
    const verbGuidance = deriveVerbGuidance(l.verbChain);
    return {
      lane: l.lane, label: l.label, description: l.description,
      interviewLabel: l.interviewLabel, executionKind: l.executionKind,
      verbChain: l.verbChain, prereqWaivers: l.prereqWaivers || [],
      flowSequence,
      verbGuidance,
      verbSteps: deriveVerbSteps(l.verbChain, flowSequence, verbGuidance),
    };
  });
}

function renderTs(model: any[]): string {
  return `// GENERATED by sidecoach/scripts/generate-lanes.ts - DO NOT EDIT BY HAND.\n` +
    `// Source: claude/hooks/sidecoach-lanes.json + sidecoach/src/verb-command-registry.ts\n` +
    `import type { FlowId } from './types';\n\n` +
    `export interface GeneratedLane {\n  lane: string; label: string; description: string;\n  interviewLabel: string; executionKind: 'sequence' | 'loop';\n  verbChain: string[]; flowSequence: FlowId[];\n  verbGuidance: { verb: string; guidance: string[] }[];\n  verbSteps: { verb: string; flowIds: FlowId[]; guidance: string[] }[];\n  prereqWaivers: { dependentFlowId: string; prerequisiteFlowId: string; reason: string }[];\n}\n\n` +
    `export const LANES: GeneratedLane[] = ${JSON.stringify(model, null, 2)};\n\n` +
    `export const LANES_BY_ID: Record<string, GeneratedLane> =\n  Object.fromEntries(LANES.map(l => [l.lane, l]));\n\n` +
    `export function getLane(id: string): GeneratedLane | undefined { return LANES_BY_ID[id]; }\n` +
    `export function getLaneFlowSequence(id: string): FlowId[] | undefined { return LANES_BY_ID[id]?.flowSequence; }\n`;
}

function renderMd(model: any[]): string {
  const rows = model.map(l =>
    `| \`${l.lane}\` | ${l.label} | ${l.executionKind} | ${l.verbChain.join(', ')} | ${l.flowSequence.join(', ')} |`).join('\n');
  return `<!-- lanes:generated:start -->\n` +
    `| Lane | Label | Kind | Verb chain | Derived flow sequence |\n|---|---|---|---|---|\n${rows}\n` +
    `<!-- lanes:generated:end -->\n`;
}

function main() {
  const check = process.argv.includes('--check');
  const model = buildModel();
  const ts = renderTs(model);
  const md = renderMd(model);
  if (check) {
    let drift = false;
    for (const [p, want] of [[TS_OUT, ts], [MD_OUT, md]] as [string, string][]) {
      const have = fs.existsSync(p) ? fs.readFileSync(p, 'utf-8') : '';
      if (have !== want) { console.error(`generate-lanes --check: DRIFT in ${path.relative(ROOT, p)}`); drift = true; }
    }
    if (drift) process.exit(1);
    console.log('generate-lanes --check: OK (no JSON/derivation/doc drift)');
    return;
  }
  fs.writeFileSync(TS_OUT, ts);
  fs.writeFileSync(MD_OUT, md);
  console.log(`generate-lanes: wrote ${path.relative(ROOT, TS_OUT)} and ${path.relative(ROOT, MD_OUT)}`);
}

if (require.main === module) main();
