// GENERATED by sidecoach/scripts/generate-enforced-rules.ts - DO NOT EDIT BY HAND.
//
// The LIVE, build-blocking mined-taste rules. Each one compiled here ONLY after the enforce-CLI
// audit verified its enforcement-ledger entry (HMAC chain + content digest) AND a passing precision
// record (>= threshold, floor, matching the ledger's signed precision-digest, current interpreter
// build). This file inlines the certified definitions as literals - it imports NO data, so the
// structural inertness invariant (src/ imports nothing from the data tier) is preserved: the ONLY
// crossing of learned data into live code is the codegen, and it is fail-closed. Regenerate via
// npm run build; a hand edit is caught by generate-enforced-rules --check (build breaks).
import type { ProductRuleDefinition } from '../product-rule-types';

export const ENFORCED_RULES: ProductRuleDefinition[] = [
  {
    "ruleId": "motion.no-scale-zero-enter",
    "sourceRuleAliases": [
      "mined:motion.no-scale-zero-enter"
    ],
    "canonicalRuleKey": "mined/no-scale-zero-enter",
    "ownerValidatorId": "polish-standard",
    "sourceVocabulary": "mined-taste",
    "sourceSeverity": "high",
    "severity": "major",
    "severityOverrideReason": "enforced via sidecoach-taste-enforce (held-out precision 1 >= threshold, human-signed); flipped from advisory to blocking",
    "findingClass": "anti-pattern",
    "registryScope": "mined-motion-enter-origin",
    "evidenceRequirements": [
      "css-rule"
    ],
    "supportedSourceKinds": [
      {
        "kind": "css",
        "level": "full"
      },
      {
        "kind": "scss",
        "level": "full"
      },
      {
        "kind": "less",
        "level": "full"
      },
      {
        "kind": "tsx",
        "level": "partial"
      },
      {
        "kind": "html",
        "level": "partial"
      }
    ],
    "scope": "file",
    "narrowTargetBehavior": "evaluate_expanded_context",
    "applicability": "not_applicable",
    "patternSpec": {
      "specVersion": 1,
      "engine": "static-css-regex",
      "applicability": {
        "anyOf": [
          "scale\\("
        ],
        "scope": "both"
      },
      "defect": {
        "anyOf": [
          {
            "pattern": "scale\\(\\s*0(?:\\.0+)?\\s*\\)",
            "flags": "i"
          }
        ]
      },
      "message": "transform: scale(0) - an element animates to or from literal zero scale, appearing or disappearing from nothing.",
      "remediation": "Scale from/to 0.9-0.97 with an opacity fade instead of literal 0; reserve a full pop for deliberate emphasis.",
      "evidenceScope": "both"
    }
  }
];

/** The ruleIds of every certified live-blocking mined-taste rule (for the runtime invariant). */
export const ENFORCED_RULE_IDS: string[] = ["motion.no-scale-zero-enter"];
