// GENERATED by sidecoach/scripts/generate-enforced-rules.ts - DO NOT EDIT BY HAND.
//
// The LIVE, build-blocking mined-taste rules. Each one compiled here ONLY after the enforce-CLI
// audit verified its enforcement-ledger entry (HMAC chain + content digest) AND a passing precision
// record (>= threshold, floor, matching the ledger's signed precision-digest, current interpreter
// build). This file inlines the certified definitions as literals - it imports NO data, so the
// structural inertness invariant (src/ imports nothing from the data tier) is preserved: the ONLY
// crossing of learned data into live code is the codegen, and it is fail-closed. Regenerate via
// npm run build; a hand edit is caught by generate-enforced-rules --check (build breaks).
import type { ProductRuleDefinition } from '../product-rule-types';

export const ENFORCED_RULES: ProductRuleDefinition[] = [];

/** The ruleIds of every certified live-blocking mined-taste rule (for the runtime invariant). */
export const ENFORCED_RULE_IDS: string[] = [];
