import { DocumentCommandHandler } from '../document-command-handler';
import * as fs from 'fs';
import * as path from 'path';
import * as os from 'os';

async function run() {
  const checks: Array<[string, boolean]> = [];
  const sandbox = fs.mkdtempSync(path.join(os.tmpdir(), 'sidecoach-document-'));

  fs.writeFileSync(path.join(sandbox, 'index.html'), `<!DOCTYPE html>
<html><head><link rel="stylesheet" href="styles.css"></head>
<body><h1>Page</h1><p>Body</p></body></html>`, 'utf-8');

  fs.writeFileSync(path.join(sandbox, 'styles.css'), `
:root {
  --color-ink: #1A1F1B;
  --color-cream: #F4EFE4;
  --color-red: #DC2618;
  --space-1: 4px;
  --space-2: 8px;
  --space-3: 16px;
  --space-4: 24px;
}
body { color: var(--color-ink); background: var(--color-cream); font-family: 'Inter', sans-serif; }
h1 { font-size: 48px; line-height: 56px; font-weight: 700; }
p { font-size: 16px; line-height: 24px; }
`, 'utf-8');

  const handler = new DocumentCommandHandler();
  const result = await handler.execute({ utterance: '/sidecoach document', projectPath: sandbox, metadata: {} } as any);

  checks.push(['T4.1: status success', result.status === 'success']);
  const designPath = path.join(sandbox, 'DESIGN.md');
  checks.push(['T4.2: DESIGN.md written', fs.existsSync(designPath)]);

  if (fs.existsSync(designPath)) {
    const content = fs.readFileSync(designPath, 'utf-8');
    checks.push(['T4.3: has YAML frontmatter', content.startsWith('---\n') && content.includes('\n---\n')]);
    checks.push(['T4.4: contains color tokens', content.includes('#1A1F1B') || content.includes('1a1f1b') || content.includes('ink')]);
    checks.push(['T4.5: contains typography', /font|typography|typeset/i.test(content)]);
    checks.push(['T4.6: contains spacing', /spacing|space/i.test(content)]);
    checks.push(['T4.7: section Overview present', content.includes('## Overview') || content.includes('# Overview')]);
    checks.push(['T4.8: section Colors present', content.includes('## Colors') || content.includes('# Colors')]);
    checks.push(['T4.9: section Typography present', content.includes('## Typography') || content.includes('# Typography')]);
    checks.push(['T4.10: NO self-attribution', !content.includes('Generated by Sidecoach')]);
  }

  fs.rmSync(sandbox, { recursive: true, force: true });

  let allPass = true;
  for (const [label, ok] of checks) {
    console.log(ok ? `PASS ${label}` : `FAIL ${label}`);
    if (!ok) allPass = false;
  }
  console.log(allPass ? 'sprint8-document-handler PASS' : 'sprint8-document-handler FAIL');
  process.exit(allPass ? 0 : 1);
}

run().catch((e) => { console.error(e); process.exit(1); });
