#!/usr/bin/env python3
"""measure-hook-corpus.py - re-derive the hook efficacy numbers from real traffic.

WHY THIS EXISTS
---------------
Four headline numbers were quoted in hook source comments as settled fact:

    grounding-gate     9.83% of envelopes vs 1.94% of genuine prompts (121 of 1231
                       vs 13 of 671)
    grounding-gate     "121 of 1231 envelopes, now 0"
    codex-watcher      33.3% of fires were false, over 4000 Bash calls
    route-intent       0% -> 22.2% recall over 627 prompts

None of them shipped with a corpus, a label set, or a script. Each existed only as
prose in a comment, and each was produced by the same agent that chose the split and
the labels. A number nobody can re-run is a claim, not a measurement.

This harness makes the mechanically-derivable half re-runnable by anyone, against
their own transcripts, with the classifying predicate committed in this file where it
can be argued with. What it deliberately does NOT do is invent labels: it never claims
a fire was "false" or that a prompt "should have routed". Those are judgments. It
prints the actual fires so a human can look at them and decide.

    exact counts you can re-derive     envelope vs genuine split, fire counts,
                                       fire rates per class
    judgments this cannot make         precision, recall, "false positive"

WHAT IT MEASURES
----------------
  --gate      grounding-gate.sh fire rate on envelopes vs genuine prompts
  --route     route-intent.sh fire rate and tier distribution over prompts
  --watcher   codex-failure-watcher.sh fire count over real Bash commands, each
              paired with a synthetic capacity failure so the OUTPUT arm of the
              trip condition is always satisfied and only the INVOCATION detector
              is under test
  --all       all three

STATE ISOLATION
---------------
Every probe gets a unique cooldown/arm file and cooldown disabled. This is not
optional hygiene: a 900s cooldown silences every probe after the first, and an
uncontrolled run has already produced a wrong measurement once.

EXIT CODES
  0  measurement completed and every hook invocation succeeded
  2  harness error - no corpus, a hook script is missing, or one or more hook
     invocations crashed/timed out//wrote to stderr, which makes the printed
     counts a statement about a broken hook rather than about the classifier
  3  nothing to measure - a selected mode had an empty denominator
"""

import argparse
import json
import os
import random
import re
import subprocess
import sys
import tempfile
import time
import unicodedata

HOOKS = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# ---------------------------------------------------------------------------
# THE CLASSIFYING PREDICATE - the load-bearing, arguable part.
#
# An "envelope" is a prompt the HARNESS delivered, not one a human typed: a teammate
# relay, a task notification, a system reminder, a context-continuation summary. It is
# defined structurally (the literal tag or the canonical sentence plus its Summary
# section), never by prose, because a genuine question can open with any words at all.
# This is the same predicate grounding-intent.json's exempt list encodes; keeping them
# in sync is the point, and a divergence here is a real finding.
#
# Anything not matching is counted as genuine. That is a deliberately generous
# definition of "genuine" - it means the envelope column can only ever UNDERCOUNT, so
# a high envelope fire rate cannot be an artifact of over-eager envelope labelling.
# ---------------------------------------------------------------------------
ENVELOPE_PATTERNS = [
    r"^\s*another claude session sent a message:\s*<teammate-message(?:>|\s)",
    r"^\s*<teammate-message(?:>|\s)",
    r"^\s*<task-notification(?:>|\s)",
    r"^\s*<system-reminder(?:>|\s)",
    r"^\s*<command-name>",
    r"^\s*<local-command-stdout>",
    r"^\s*base directory for this skill:\s*[~/][^\s]*\s",
    r"^\s*this session is being continued from a previous conversation that ran "
    r"out of context\.[\s\S]{0,2000}?\bsummary:",
    r"^\s*caveat: the messages below were generated by the user while running",
]
_ENVELOPE_RE = [re.compile(p, re.IGNORECASE) for p in ENVELOPE_PATTERNS]


def strip_lead_invisible(s):
    """Same rule the hooks use: drop leading whitespace and Unicode format chars.

    A hardcoded list drifts. Category Cf covers BOM, the zero-widths and the
    directional marks; Zs covers exotic spaces.
    """
    i = 0
    while i < len(s) and (s[i].isspace() or unicodedata.category(s[i]) in ("Cf", "Zs")):
        i += 1
    return s[i:]


def is_envelope(prompt):
    return any(r.search(strip_lead_invisible(prompt)) for r in _ENVELOPE_RE)


# The predicate above is deliberately INDEPENDENT of the hooks - measuring a hook
# with its own exemption list would be circular. Independence is only useful while
# the two stay in step on what an envelope IS, so the drift is reported rather than
# left to rot. Codex review 2026-07-28: the harness was missing the skill-injection
# marker the hooks had, so every injected skill body counted as "genuine" and the
# genuine fire rate was inflated.
LEXICONS = {
    "grounding-intent.json": "exempt",
    "route-intent.json": "envelope_exempt",
}


def report_predicate_drift():
    mine = set(ENVELOPE_PATTERNS)
    drift = []
    for fname, key in LEXICONS.items():
        path = os.path.join(HOOKS, fname)
        try:
            with open(path) as fh:
                pats = json.load(fh).get(key) or []
        except Exception as e:
            drift.append(f"  {fname}: could not read {key} ({e})")
            continue
        for pat in pats:
            if pat not in mine:
                drift.append(f"  {fname}:{key} has a pattern this harness does not: {pat}")
    if drift:
        print("\nPREDICATE DRIFT (the split below may be miscounted):")
        print("\n".join(drift))
    return drift


def iter_transcripts(corpus):
    """Yield transcripts in a STABLE order.

    os.walk order follows the filesystem, so --sample with a fixed seed picked a
    different set after any directory rewrite - a "seeded, reproducible" claim that
    was not true. Sorting makes it true.
    """
    out = []
    for root, dirs, files in os.walk(corpus):
        dirs.sort()
        for f in sorted(files):
            if f.endswith(".jsonl"):
                out.append(os.path.join(root, f))
    return sorted(out)


def collect(corpus):
    """Return (prompts, bash_commands) harvested from every transcript."""
    prompts, commands = [], []
    for path in iter_transcripts(corpus):
        try:
            fh = open(path, errors="replace")
        except OSError:
            continue
        with fh:
            for line in fh:
                try:
                    d = json.loads(line)
                except Exception:
                    continue
                t = d.get("type")
                msg = d.get("message") or {}
                if t == "user":
                    c = msg.get("content")
                    text = None
                    if isinstance(c, str):
                        text = c
                    elif isinstance(c, list):
                        parts = [b.get("text", "") for b in c
                                 if isinstance(b, dict) and b.get("type") == "text"]
                        text = "\n".join(p for p in parts if p) if parts else None
                    if text and text.strip():
                        prompts.append(text)
                elif t == "assistant":
                    for b in (msg.get("content") or []):
                        if (isinstance(b, dict) and b.get("type") == "tool_use"
                                and b.get("name") == "Bash"):
                            cmd = (b.get("input") or {}).get("command")
                            if isinstance(cmd, str) and cmd.strip():
                                commands.append(cmd)
    return prompts, commands


# Hook-control variables the CALLER might have set. Inheriting them would silently
# measure someone's experiment while labelling the result "route-intent.sh"
# (Codex review). Every probe starts from a known state.
_SCRUB_PREFIXES = ("ROUTE_INTENT_", "GROUNDING_", "CODEX_WATCHER_", "SIDECOACH_")

# A hook that CRASHES is not a hook that stayed silent. Counting a syntax error, a
# missing lexicon or a timeout as "did not fire" turns the whole run into a vacuous
# zero that still exits 0 - the single worst outcome for a tool whose only job is to
# be trustworthy. Every such event lands here and fails the run.
ERRORS = []


def run_hook(script, payload, env_extra, statefiles, label=""):
    """Run a hook once with isolated state. Returns (stdout, stderr, rc)."""
    env = {k: v for k, v in os.environ.items()
           if not k.startswith(_SCRUB_PREFIXES)}
    env.update(env_extra)
    for f in statefiles:
        try:
            os.unlink(f)
        except OSError:
            pass
    try:
        p = subprocess.run(["/bin/bash", script], input=payload.encode(),
                           stdout=subprocess.PIPE, stderr=subprocess.PIPE,
                           timeout=30, env=env)
        out = p.stdout.decode(errors="replace")
        err = p.stderr.decode(errors="replace")
        if p.returncode != 0 or err.strip():
            ERRORS.append(f"{os.path.basename(script)} rc={p.returncode} "
                          f"stderr={err.strip()[:200]!r} on {label[:80]!r}")
        return out, err, p.returncode
    except subprocess.TimeoutExpired:
        ERRORS.append(f"{os.path.basename(script)} TIMED OUT on {label[:80]!r}")
        return "", "TIMEOUT", -1


def pct(n, d):
    return f"{(100.0 * n / d):.2f}%" if d else "n/a"


def measure_gate(prompts, tmp, show):
    script = os.path.join(HOOKS, "grounding-gate.sh")
    if not os.path.exists(script):
        ERRORS.append(f"hook script missing: {script}")
        return None
    arm = os.path.join(tmp, "gate.arm")
    cool = os.path.join(tmp, "gate.cool")
    env = {"GROUNDING_ARM_FILE": arm, "GROUNDING_COOLDOWN_FILE": cool,
           "GROUNDING_COOLDOWN": "0"}
    counts = {"envelope": [0, 0], "genuine": [0, 0]}   # [total, fired]
    fires = {"envelope": [], "genuine": []}
    for pr in prompts:
        cls = "envelope" if is_envelope(pr) else "genuine"
        counts[cls][0] += 1
        out, _err, _rc = run_hook(script, json.dumps({"prompt": pr}), env, [arm, cool], pr)
        if out.strip():
            counts[cls][1] += 1
            if len(fires[cls]) < show:
                fires[cls].append(pr[:160].replace("\n", " "))
    print("\n=== grounding-gate.sh ===")
    print(f"{'class':<10} {'prompts':>8} {'fired':>7} {'rate':>9}")
    for cls in ("envelope", "genuine"):
        tot, fired = counts[cls]
        print(f"{cls:<10} {tot:>8} {fired:>7} {pct(fired, tot):>9}")
    print("\nThe gate must be SILENT on envelopes. Any nonzero envelope count is a defect.")
    for cls in ("envelope", "genuine"):
        if fires[cls]:
            print(f"\n  sample {cls} fires (for human inspection, not auto-labelled):")
            for s in fires[cls]:
                print(f"    - {s}")
    return counts


def measure_route(prompts, tmp, show):
    script = os.path.join(HOOKS, "route-intent.sh")
    if not os.path.exists(script):
        ERRORS.append(f"hook script missing: {script}")
        return None
    cool = os.path.join(tmp, "route.cool")
    env = {"ROUTE_INTENT_COOLDOWN_FILE": cool, "ROUTE_INTENT_COOLDOWN": "0"}
    total = fired = 0
    by_class = {"envelope": [0, 0], "genuine": [0, 0]}
    tiers = {}
    samples = []
    for pr in prompts:
        cls = "envelope" if is_envelope(pr) else "genuine"
        total += 1
        by_class[cls][0] += 1
        out, _err, _rc = run_hook(script, json.dumps({"prompt": pr}), env, [cool], pr)
        if out.strip():
            fired += 1
            by_class[cls][1] += 1
            m = re.search(r"reads as ([^.]+)\.", out)
            tier = m.group(1) if m else "unknown"
            tiers[tier] = tiers.get(tier, 0) + 1
            if len(samples) < show:
                samples.append((tier, pr[:160].replace("\n", " ")))
    print("\n=== route-intent.sh ===")
    print(f"prompts measured: {total}")
    print(f"routed:           {fired}  ({pct(fired, total)})")
    print(f"{'class':<10} {'prompts':>8} {'routed':>7} {'rate':>9}")
    for cls in ("envelope", "genuine"):
        t, f = by_class[cls]
        print(f"{cls:<10} {t:>8} {f:>7} {pct(f, t):>9}")
    if tiers:
        print("\n  tier distribution:")
        for k, v in sorted(tiers.items(), key=lambda kv: -kv[1]):
            print(f"    {v:>5}  {k}")
    if samples:
        print("\n  sample routes (for human inspection, NOT labelled correct/incorrect):")
        for tier, s in samples:
            print(f"    [{tier}] {s}")
    return {"total": total, "fired": fired, "by_class": by_class}


CAPACITY = "ERROR: Selected model is at capacity. Please try again."


def measure_watcher(commands, show):
    script = os.path.join(HOOKS, "codex-failure-watcher.sh")
    if not os.path.exists(script):
        ERRORS.append(f"hook script missing: {script}")
        return None
    # Only commands that mention codex can possibly trip it; the rest are counted but
    # not executed, which keeps a 19k-call corpus tractable without changing any count.
    mentions = [c for c in commands if "codex" in c.lower()]
    fired = 0
    samples = []
    for cmd in mentions:
        payload = json.dumps({"tool_name": "Bash", "tool_input": {"command": cmd},
                              "tool_response": {"stdout": CAPACITY}})
        out, _err, _rc = run_hook(script, payload, {}, [], cmd)
        if "CODEX FAILURE DETECTED" in out:
            fired += 1
            if len(samples) < show:
                samples.append(cmd[:200].replace("\n", " "))
    print("\n=== codex-failure-watcher.sh ===")
    print(f"Bash calls in corpus:      {len(commands)}")
    print(f"...mentioning codex:       {len(mentions)}  ({pct(len(mentions), len(commands))})")
    print(f"...detected as invocation: {fired}  "
          f"({pct(fired, len(mentions))} of mentions, "
          f"{pct(fired, len(commands))} of all Bash calls)")
    print("\nEvery call is paired with a synthetic capacity failure, so this isolates the")
    print("INVOCATION detector. Read the samples to judge them; the harness does not.")
    if samples:
        print("\n  sample detections (for human inspection, not auto-labelled):")
        for s in samples:
            print(f"    - {s}")
    return {"bash": len(commands), "mentions": len(mentions), "fired": fired}


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--corpus", default=os.path.expanduser("~/.claude/projects"),
                    help="transcript root (default: ~/.claude/projects)")
    ap.add_argument("--gate", action="store_true")
    ap.add_argument("--route", action="store_true")
    ap.add_argument("--watcher", action="store_true")
    ap.add_argument("--all", action="store_true")
    ap.add_argument("--sample", type=int, default=0,
                    help="measure a random sample of N prompts instead of all "
                         "(seeded, so a rerun with the same N gives the same set)")
    ap.add_argument("--seed", type=int, default=20260728)
    ap.add_argument("--show", type=int, default=5,
                    help="how many example fires to print per class")
    args = ap.parse_args()

    if not (args.gate or args.route or args.watcher or args.all):
        args.all = True
    if not os.path.isdir(args.corpus):
        print(f"HARNESS ERROR: no corpus at {args.corpus}", file=sys.stderr)
        return 2

    t0 = time.time()
    prompts, commands = collect(args.corpus)
    if not prompts and not commands:
        print(f"NOTHING TO MEASURE: {args.corpus} yielded no prompts or Bash calls",
              file=sys.stderr)
        return 3

    print(f"corpus:  {args.corpus}")
    print(f"prompts: {len(prompts)}   bash calls: {len(commands)}   "
          f"harvest: {time.time() - t0:.1f}s")
    report_predicate_drift()
    env_n = sum(1 for p in prompts if is_envelope(p))
    print(f"split:   {env_n} envelope / {len(prompts) - env_n} genuine "
          f"(predicate: ENVELOPE_PATTERNS in this file)")

    if args.sample and args.sample < len(prompts):
        random.Random(args.seed).shuffle(prompts)
        prompts = prompts[:args.sample]
        print(f"SAMPLED: {len(prompts)} prompts (seed {args.seed}) - "
              f"a sample is an estimate, the full run is the auditable number")

    # A measurement with an empty denominator is not a zero, it is a non-answer.
    # `--gate` over a corpus of nothing but Bash calls used to print "n/a" and exit 0
    # (Codex review), which reads exactly like a clean result.
    empty = []
    if (args.all or args.gate) and not prompts:
        empty.append("--gate needs prompts, corpus had none")
    if (args.all or args.route) and not prompts:
        empty.append("--route needs prompts, corpus had none")
    if (args.all or args.watcher) and not commands:
        empty.append("--watcher needs Bash calls, corpus had none")
    if empty:
        print("NOTHING TO MEASURE:", file=sys.stderr)
        for e in empty:
            print("  " + e, file=sys.stderr)
        return 3

    if args.all or args.gate:
        measure_gate(prompts, tempfile.mkdtemp(), args.show)
    if args.all or args.route:
        measure_route(prompts, tempfile.mkdtemp(), args.show)
    if args.all or args.watcher:
        measure_watcher(commands, args.show)

    print(f"\ntotal elapsed: {time.time() - t0:.1f}s")

    # A hook that crashed, timed out or wrote to stderr makes every count above a
    # statement about a broken hook, not about the classifier. Say so and fail.
    if ERRORS:
        uniq = sorted(set(ERRORS))
        print(f"\nMEASUREMENT INVALID: {len(ERRORS)} hook invocation(s) failed. "
              f"The numbers above are NOT a valid measurement.", file=sys.stderr)
        for e in uniq[:10]:
            print("  " + e, file=sys.stderr)
        if len(uniq) > 10:
            print(f"  ... and {len(uniq) - 10} more distinct failures", file=sys.stderr)
        return 2
    return 0


if __name__ == "__main__":
    sys.exit(main())
