#!/bin/bash
# PreToolUse hook for Write|Edit|MultiEdit. Blocks file content matching forbidden
# patterns from CLAUDE.md: emojis, emdashes, attribution lines, legacy model IDs.
# Reads hook input JSON from stdin, emits permissionDecision JSON to stdout.

INPUT=$(cat)
printf '%s' "$INPUT" | python3 -c '
import json, sys, re

try:
    data = json.load(sys.stdin)
except Exception:
    print("{}"); sys.exit(0)

tool = data.get("tool_name", "")
inp  = data.get("tool_input", {})

if tool == "Write":
    content = inp.get("content", "")
elif tool == "Edit":
    content = inp.get("new_string", "")
elif tool == "MultiEdit":
    edits = inp.get("edits", []) or []
    content = "\n".join((e or {}).get("new_string", "") for e in edits)
else:
    print("{}"); sys.exit(0)

if not content:
    print("{}"); sys.exit(0)


reason = None

for needle, msg in [
    ("Co-Authored-By",        "Co-Authored-By attribution forbidden by CLAUDE.md"),
    ("Generated with Claude", "Claude attribution forbidden by CLAUDE.md"),
    ("Generated by Claude",   "Claude attribution forbidden by CLAUDE.md"),
]:
    if needle in content:
        reason = msg; break

if not reason and ("\u2014" in content or "\u2013" in content):
    reason = "Emdash/endash forbidden by CLAUDE.md - use hyphens or rewrite"

if not reason:
    if re.search(r"gpt-4o(?!-mini-tts)|gpt-4\.1|gpt-3\.5|gpt-4(?![o\.\-\d])|claude-3-(opus|sonnet|haiku)", content):
        reason = "Legacy model ID forbidden by CLAUDE.md - use latest model versions only"

if not reason:
    # Emoji detection by EMOJI-PRESENTATION, not by Unicode block. Terminal
    # typography is allowed - check (U+2713), ballot-x (U+2717), stars, arrows,
    # box-drawing, geometric shapes, dingbat asterisks - because these are
    # text-presentation symbols, not emoji. A character is treated as emoji only
    # when it is genuinely a color pictograph:
    #   - the supplementary emoji planes (U+1F000..U+1FAFF);
    #   - it carries a Variation-Selector-16 (U+FE0F) or combining keycap
    #     (U+20E3) - these force/define emoji presentation (warning+VS16, etc.);
    #   - it is one of the BMP code points that are color-emoji BY DEFAULT
    #     (Unicode Emoji_Presentation=Yes), enumerated below.
    # Everything else passes. KEEP IN SYNC with content-guard-stop.sh.
    _EMOJI_PRES = (
        (0x231A, 0x231B), (0x23E9, 0x23EC), (0x23F0, 0x23F0), (0x23F3, 0x23F3),
        (0x25FD, 0x25FE), (0x2614, 0x2615), (0x2648, 0x2653), (0x267F, 0x267F),
        (0x2693, 0x2693), (0x26A1, 0x26A1), (0x26AA, 0x26AB), (0x26BD, 0x26BE),
        (0x26C4, 0x26C5), (0x26CE, 0x26CE), (0x26D4, 0x26D4), (0x26EA, 0x26EA),
        (0x26F2, 0x26F3), (0x26F5, 0x26F5), (0x26FA, 0x26FA), (0x26FD, 0x26FD),
        (0x2705, 0x2705), (0x270A, 0x270B), (0x2728, 0x2728), (0x274C, 0x274C),
        (0x274E, 0x274E), (0x2753, 0x2755), (0x2757, 0x2757), (0x2795, 0x2797),
        (0x27B0, 0x27B0), (0x27BF, 0x27BF), (0x2B1B, 0x2B1C), (0x2B50, 0x2B50),
        (0x2B55, 0x2B55),
    )
    def _emoji(s):
        for ch in s:
            cp = ord(ch)
            if cp == 0xFE0F or cp == 0x20E3:        # VS16 / combining keycap -> emoji
                return ch
            if 0x1F000 <= cp <= 0x1FAFF:            # supplementary emoji planes
                return ch
            for lo, hi in _EMOJI_PRES:
                if lo <= cp <= hi:
                    return ch
        return None
    bad = _emoji(content)
    if bad:
        reason = "Emoji (" + repr(bad) + ") forbidden by CLAUDE.md"

if reason:
    print(json.dumps({
        "hookSpecificOutput": {
            "hookEventName": "PreToolUse",
            "permissionDecision": "deny",
            "permissionDecisionReason": "BLOCKED: " + reason
        }
    }))
else:
    print("{}")
'
