// GENERATED by sidecoach/scripts/generate-counter-rules.ts - DO NOT EDIT BY HAND.
// Source: eval/corpus/defect-distribution.json (Stage 1b), generatedUtc 2026-07-25T23:21:17.012Z
// Thresholds: rate >= 0.3 over >= 5 conclusive pages.
//
// A CounterRule names a taste/objective class a given provider systematically over-produces, so the
// orchestrator can append its guidance WHEN the active model's provider matches. Every 'rule' is a class the
// shipping scanner detects (validated at generation time + by counter-rules.test.ts against the registry).

export interface CounterRule { provider: string; rule: string; fired: number; total: number; rate: number; guidance: string; }

export const COUNTER_RULE_RATE_MIN = 0.3;
export const COUNTER_RULE_MIN_TOTAL = 5;

export const COUNTER_RULES: CounterRule[] = [
  {
    "provider": "claude",
    "rule": "default-typeface",
    "fired": 20,
    "total": 20,
    "rate": 1,
    "guidance": "watch default-typeface: claude pages fired it on 100% of the sample (20/20) - counter it deliberately"
  },
  {
    "provider": "claude",
    "rule": "low-contrast",
    "fired": 11,
    "total": 20,
    "rate": 0.55,
    "guidance": "watch low-contrast: claude pages fired it on 55% of the sample (11/20) - counter it deliberately"
  },
  {
    "provider": "claude",
    "rule": "nested-cards",
    "fired": 7,
    "total": 20,
    "rate": 0.35,
    "guidance": "watch nested-cards: claude pages fired it on 35% of the sample (7/20) - counter it deliberately"
  },
  {
    "provider": "claude",
    "rule": "gray-on-color",
    "fired": 6,
    "total": 20,
    "rate": 0.3,
    "guidance": "watch gray-on-color: claude pages fired it on 30% of the sample (6/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "default-typeface",
    "fired": 19,
    "total": 20,
    "rate": 0.95,
    "guidance": "watch default-typeface: gemini pages fired it on 95% of the sample (19/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "low-contrast",
    "fired": 15,
    "total": 20,
    "rate": 0.75,
    "guidance": "watch low-contrast: gemini pages fired it on 75% of the sample (15/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "nested-cards",
    "fired": 12,
    "total": 20,
    "rate": 0.6,
    "guidance": "watch nested-cards: gemini pages fired it on 60% of the sample (12/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "skipped-heading",
    "fired": 10,
    "total": 20,
    "rate": 0.5,
    "guidance": "watch skipped-heading: gemini pages fired it on 50% of the sample (10/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "tiny-text",
    "fired": 8,
    "total": 20,
    "rate": 0.4,
    "guidance": "watch tiny-text: gemini pages fired it on 40% of the sample (8/20) - counter it deliberately"
  },
  {
    "provider": "gemini",
    "rule": "gray-on-color",
    "fired": 6,
    "total": 20,
    "rate": 0.3,
    "guidance": "watch gray-on-color: gemini pages fired it on 30% of the sample (6/20) - counter it deliberately"
  },
  {
    "provider": "gpt",
    "rule": "default-typeface",
    "fired": 18,
    "total": 20,
    "rate": 0.9,
    "guidance": "watch default-typeface: gpt pages fired it on 90% of the sample (18/20) - counter it deliberately"
  },
  {
    "provider": "gpt",
    "rule": "nested-cards",
    "fired": 15,
    "total": 20,
    "rate": 0.75,
    "guidance": "watch nested-cards: gpt pages fired it on 75% of the sample (15/20) - counter it deliberately"
  },
  {
    "provider": "gpt",
    "rule": "soft-radial-glow",
    "fired": 10,
    "total": 20,
    "rate": 0.5,
    "guidance": "watch soft-radial-glow: gpt pages fired it on 50% of the sample (10/20) - counter it deliberately"
  }
];

/** The classes provider P over-produces, most-fired first. */
export function counterRulesForProvider(provider: string): CounterRule[] {
  return COUNTER_RULES.filter((r) => r.provider === provider);
}

/** The "watch <class>" guidance lines for provider P (empty when P has no over-produced class). */
export function counterRuleGuidanceForProvider(provider: string): string[] {
  return counterRulesForProvider(provider).map((r) => r.guidance);
}
