// sidecoach/src/counter-rule-generation.ts
//
// PURE logic for Stage 1c counter-rule compilation (upgrade plan 2026-07-23, Stage 1c). Lives under src/ (inside
// the tsc rootDir) so counter-rules.test.ts imports it without TS6059 - the exact split generate-validators.ts uses
// with validator-generation.ts. scripts/generate-counter-rules.ts is the thin I/O + --check wrapper over these fns.
//
// A CounterRule names a taste/objective class a given provider systematically OVER-PRODUCES (fire-rate at/above a
// frozen threshold, over a minimum sample), derived from the Stage 1b defect-distribution artifact. The orchestrator
// can append a provider's guidance WHEN the active model's provider matches.

// COUNTER_RULE_RATE_MIN: a class a provider fires on at least this share of its CONCLUSIVE pages is a systematic
// tendency worth a guidance line, not an incidental one-off. COUNTER_RULE_MIN_TOTAL: ignore a rate from too few
// conclusive pages (a 1/2 = 0.50 is noise) - require a real denominator before a rate can promote a class. Both are
// frozen operating points, calibrated against the real Stage 1b distribution to keep the emitted set focused (the
// plan's "keep to ~17 classes, never a 59-line hand list").
export const COUNTER_RULE_RATE_MIN = 0.30;
export const COUNTER_RULE_MIN_TOTAL = 5;

export interface RuleCell { fired: number; total: number; rate: number | null }
export interface DistArtifact {
  schema: string;
  generatedUtc: string;
  ruleUniverse: string[];
  distribution: Record<string, Record<string, RuleCell>>;
}
export interface CounterRule {
  provider: string;
  rule: string;
  fired: number;
  total: number;
  rate: number;   // fired/total, in [COUNTER_RULE_RATE_MIN, 1]
  guidance: string;
}

/** Derive the counter-rule set from a distribution artifact. Deterministic order: provider asc, rate desc, rule asc.
 *  Throws on a distribution that names a class outside its own ruleUniverse (a corrupt artifact must fail the build,
 *  never silently emit a class the product does not detect). */
export function deriveCounterRules(art: DistArtifact): CounterRule[] {
  const universe = new Set(art.ruleUniverse);
  const out: CounterRule[] = [];
  for (const [provider, rules] of Object.entries(art.distribution)) {
    for (const [rule, cell] of Object.entries(rules)) {
      if (!universe.has(rule)) {
        throw new Error(`counter-rules: distribution class '${rule}' is absent from ruleUniverse (corrupt artifact)`);
      }
      if (cell.rate === null || cell.total < COUNTER_RULE_MIN_TOTAL || cell.rate < COUNTER_RULE_RATE_MIN) continue;
      const pct = Math.round(cell.rate * 100);
      out.push({
        provider, rule, fired: cell.fired, total: cell.total, rate: cell.rate,
        guidance: `watch ${rule}: ${provider} pages fired it on ${pct}% of the sample (${cell.fired}/${cell.total}) - counter it deliberately`,
      });
    }
  }
  out.sort((a, b) => (a.provider < b.provider ? -1 : a.provider > b.provider ? 1 : (b.rate - a.rate) || (a.rule < b.rule ? -1 : a.rule > b.rule ? 1 : 0)));
  return out;
}

/** Render the generated product module text. Embeds only STABLE inputs (the artifact's own generatedUtc + the frozen
 *  thresholds), never new Date(), so re-running on the same distribution is byte-identical and --check is meaningful. */
export function renderCounterRulesModule(art: DistArtifact, rules: CounterRule[]): string {
  return (
    `// GENERATED by sidecoach/scripts/generate-counter-rules.ts - DO NOT EDIT BY HAND.\n` +
    `// Source: eval/corpus/defect-distribution.json (Stage 1b), generatedUtc ${art.generatedUtc}\n` +
    `// Thresholds: rate >= ${COUNTER_RULE_RATE_MIN} over >= ${COUNTER_RULE_MIN_TOTAL} conclusive pages.\n` +
    `//\n` +
    `// A CounterRule names a taste/objective class a given provider systematically over-produces, so the\n` +
    `// orchestrator can append its guidance WHEN the active model's provider matches. Every 'rule' is a class the\n` +
    `// shipping scanner detects (validated at generation time + by counter-rules.test.ts against the registry).\n\n` +
    `export interface CounterRule { provider: string; rule: string; fired: number; total: number; rate: number; guidance: string; }\n\n` +
    `export const COUNTER_RULE_RATE_MIN = ${COUNTER_RULE_RATE_MIN};\n` +
    `export const COUNTER_RULE_MIN_TOTAL = ${COUNTER_RULE_MIN_TOTAL};\n\n` +
    `export const COUNTER_RULES: CounterRule[] = ${JSON.stringify(rules, null, 2)};\n\n` +
    `/** The classes provider P over-produces, most-fired first. */\n` +
    `export function counterRulesForProvider(provider: string): CounterRule[] {\n` +
    `  return COUNTER_RULES.filter((r) => r.provider === provider);\n` +
    `}\n\n` +
    `/** The "watch <class>" guidance lines for provider P (empty when P has no over-produced class). */\n` +
    `export function counterRuleGuidanceForProvider(provider: string): string[] {\n` +
    `  return counterRulesForProvider(provider).map((r) => r.guidance);\n` +
    `}\n`
  );
}
