import { Flow, FlowId } from './types';

// Flow registry. Post-T-0015 cull (2026-05-28):
// - 12 legacy number-prefixed flows removed as duplicates of lettered canonicals.
// - 2 unique legacy flows renamed with the next letter prefix (flow4 -> flowY, flow7 -> flowZ).
// - Final count: 26 flows. See claude/skills/sidecoach/CHEATSHEET.md for the per-tier list.

export const flows: Flow[] = [
  // TIER 1: STRATEGY/RESEARCH
  {
    id: 'flowA_brand_verify',
    name: 'Brand/PRODUCT.md Verification',
    description: 'Verify project has valid brand register before design work',
    triggers: {
      patterns: [
        'check brand[s]',
        'verify [brand/product] register',
        'validate brand',
        'do i have product.md',
        'check project setup',
        'verify design foundation',
        'initialize brand',
      ],
      intentMarkers: ['brand', 'verify', 'register', 'product.md', 'setup', 'foundation', 'initialize'],
      avoidCollisionWith: ['flowB_component_research', 'flowE_motion_patterns'],
      negativeFilters: ['design', 'component', 'implement'],
    },
  },
  {
    id: 'flowB_component_research',
    name: 'Component Research (component.gallery)',
    description: 'Research component patterns and implementations (60 types, 95 systems)',
    triggers: {
      patterns: [
        'research [component/pattern]',
        'find [component] examples',
        'component gallery search [pattern]',
        '[component] patterns',
        'what components exist for [use case]',
        '[component] accessibility baseline',
        'component recommendations for [constraint]',
      ],
      intentMarkers: ['research', 'component', 'gallery', 'examples', 'patterns', 'baseline', 'recommendations'],
      avoidCollisionWith: ['flowC_font_research', 'flowZ_design_component'],
      negativeFilters: ['design', 'implement', 'build'],
    },
  },
  {
    id: 'flowC_font_research',
    name: 'Font Research (fontshare.com)',
    description: 'Research typefaces and pairing against brand personality',
    triggers: {
      patterns: [
        'research fonts',
        'find typeface for [brand/use case]',
        'fontshare search [style]',
        'font pairing for [brand]',
        '[font] weights and licensing',
        'typography research for [project]',
        'what fonts match [personality]',
      ],
      intentMarkers: ['font', 'typeface', 'fontshare', 'pairing', 'weights', 'typography', 'licensing'],
      avoidCollisionWith: ['flowD_reference_inspiration', 'flowB_component_research'],
      negativeFilters: ['design', 'implement', 'set font'],
    },
  },
  {
    id: 'flowD_reference_inspiration',
    name: 'Reference/Inspiration Search (design-references)',
    description: 'Search personal design reference catalog for patterns and inspiration',
    triggers: {
      patterns: [
        'search references for [pattern]',
        'curate [design aspect]',
        'find inspiration for [element]',
        'reference search [concept]',
        'design patterns catalog [query]',
        'show me examples of [style]',
        'inspiration for [design task]',
      ],
      intentMarkers: ['reference', 'inspiration', 'curate', 'search', 'catalog', 'examples', 'patterns'],
      avoidCollisionWith: ['flowE_motion_patterns', 'flowZ_design_component'],
      negativeFilters: ['implement', 'design', 'build'],
    },
  },
  {
    id: 'flowE_motion_patterns',
    name: 'Motion Pattern Library (GSAP/Lenis)',
    description: 'Research motion patterns and animation techniques (tweens, ScrollTrigger, Flip, SplitText, DrawSVG)',
    triggers: {
      patterns: [
        'motion patterns for [element]',
        'GSAP examples for [animation]',
        'scrolltrigger pattern [concept]',
        'animation library [effect]',
        'motion research for [interaction]',
        'smooth scroll patterns',
        'flip animation examples',
      ],
      intentMarkers: ['motion', 'GSAP', 'animation', 'scroll', 'pattern', 'library', 'effect'],
      avoidCollisionWith: ['flowH_motion_integration', 'flowB_component_research'],
      negativeFilters: ['implement', 'build', 'code'],
    },
  },

  // TIER 2: EXECUTION
  {
    id: 'flowF_design_tokens',
    name: 'Design System Tokens (DESIGN.md)',
    description: 'Full DESIGN.md workflow - extract, manage, lint tokens (google-labs-code spec). Absorbed flow11_extract_tokens.',
    triggers: {
      patterns: [
        'extract design tokens',
        'create design.md',
        'manage design tokens',
        'token extraction from [design]',
        'validate tokens against [standard]',
        'lint design.md',
        'token consistency check',
        'extract [pattern] to token',
        'standardize [pattern]',
      ],
      intentMarkers: ['token', 'design.md', 'extract', 'manage', 'lint', 'consistency', 'validate', 'standardize', 'reusable'],
      avoidCollisionWith: ['flowG_component_implementation'],
      negativeFilters: ['implement', 'build', 'component'],
    },
  },
  {
    id: 'flowG_component_implementation',
    name: 'Component Implementation',
    description: 'Map design spec to implementation, wire variants, states, responsive behavior. Absorbed flow10_implement_design.',
    triggers: {
      patterns: [
        'implement [component] from design',
        'code component [name]',
        'build [component] with states',
        'component implementation for [design]',
        'wire variants of [component]',
        'make [component] responsive',
        'component implementation checklist',
        'build from [Figma/reference]',
        '[component] from [design source]',
      ],
      intentMarkers: ['implement', 'component', 'code', 'variants', 'states', 'responsive', 'wire', 'build from'],
      avoidCollisionWith: ['flowZ_design_component', 'flowO_clone_match_special'],
      negativeFilters: ['design', 'clone', 'exact'],
    },
  },
  {
    id: 'flowH_motion_integration',
    name: 'Motion Integration (GSAP/Lenis)',
    description: 'Implement production-ready motion - tweens, ScrollTrigger, Flip, SplitText, DrawSVG',
    triggers: {
      patterns: [
        'add motion to [element]',
        'implement GSAP animation',
        'scrolltrigger for [element]',
        'motion implementation for [interaction]',
        'integrate smooth scroll',
        'animate [element] with DrawSVG',
        'production motion code',
      ],
      intentMarkers: ['motion', 'animation', 'GSAP', 'scroll', 'tweens', 'implement', 'integrate'],
      avoidCollisionWith: ['flowE_motion_patterns', 'flowJ_tactical_polish'],
      negativeFilters: ['research', 'pattern', 'example'],
    },
  },
  {
    id: 'flowI_accessibility',
    name: 'Accessibility Compliance (WCAG 2.1 AA)',
    description: 'WCAG 2.1 AA validation, screen reader testing, severity prioritization. Absorbed flow9_accessible.',
    triggers: {
      patterns: [
        'make [area] accessible',
        'a11y audit [area]',
        'accessibility check [element]',
        'screen reader test [area]',
        'WCAG [AA/AAA] [area]',
        'fix a11y issues',
        'semantic HTML validation',
        '[area] needs keyboard navigation',
      ],
      intentMarkers: ['accessible', 'a11y', 'screen reader', 'WCAG', 'semantic', 'keyboard', 'aria'],
      avoidCollisionWith: ['flowK_multi_lens_audit'],
      negativeFilters: ['audit [generic]', 'improve [generic]', 'layout'],
    },
  },

  // TIER 3: POLISH/QA
  {
    id: 'flowJ_tactical_polish',
    name: '16-Point Tactical Polish',
    description: 'All make-interfaces-feel-better rules: concentric radius, optical alignment, shadows, animations, hit areas, icons, numbers, wrapping, outlines, scale, motion, transitions, will-change. Absorbed flow2_polish_enhance.',
    triggers: {
      patterns: [
        'polish [element]',
        'make this feel better',
        'tactical refinement of [element]',
        'apply polish rules',
        '[element] 16-point check',
        'interface feel improvement',
        'micro-interaction polish',
        'apply make-interfaces-feel-better',
        'add feeling to [element]',
        'enhance interaction on [element]',
        '[element] needs more life',
        'make [element] less janky',
      ],
      intentMarkers: ['polish', 'feel better', 'tactical', 'refinement', '16-point', 'micro-interaction', 'feel', 'life', 'janky', 'microinteraction'],
      avoidCollisionWith: ['flowK_multi_lens_audit', 'flowH_motion_integration'],
      negativeFilters: ['audit', 'design', 'implement', 'layout'],
    },
  },
  {
    id: 'flowK_multi_lens_audit',
    name: 'Multi-Lens Audit (5 dimensions)',
    description: 'Technical scan - accessibility, performance, theming, responsive, anti-patterns (addresses all Critical/High findings). Absorbed flow3_audit_page and flow5_review_qa.',
    triggers: {
      patterns: [
        'multi-lens audit [area]',
        'technical audit [area]',
        '5-dimension audit',
        'comprehensive technical check',
        'find all issues in [area]',
        'detect anti-patterns in [area]',
        'performance/a11y/responsive audit',
        'audit [page/section]',
        'review [area] for issues',
        'QA check [area]',
        'review this PR',
        'code review [area]',
        'comprehensive check of [area]',
      ],
      intentMarkers: ['multi-lens', 'audit', 'technical', '5-dimension', 'anti-pattern', 'comprehensive', 'qa check', 'code review'],
      avoidCollisionWith: ['flowI_accessibility', 'flowL_design_critique'],
      negativeFilters: ['design', 'polish', 'improvement'],
    },
  },
  {
    id: 'flowL_design_critique',
    name: 'Design Critique (Nielsen heuristics)',
    description: 'Independent design review - Nielsen heuristics, AI-slop detection, cognitive load, emotional journey',
    triggers: {
      patterns: [
        'design critique [area]',
        'review [design] for quality',
        'Nielsen heuristics check',
        'ai-slop detection for [area]',
        'cognitive load assessment',
        'emotional journey mapping',
        'independent design review',
      ],
      intentMarkers: ['critique', 'review', 'Nielsen', 'heuristics', 'cognitive', 'emotional', 'quality'],
      avoidCollisionWith: ['flowK_multi_lens_audit'],
      negativeFilters: ['audit', 'implement', 'code'],
    },
  },
  {
    id: 'flowM_responsive_validation',
    name: 'Responsive Design Validation',
    description: 'Breakpoint testing (from DESIGN.md), touch target verification (40x40px minimum), viewport behavior. Absorbed flow12_responsive_review.',
    triggers: {
      patterns: [
        'responsive validation [area]',
        'breakpoint test [area]',
        'touch target check',
        'viewport behavior test',
        'mobile/tablet/desktop validation',
        'responsive review [area]',
        '40x40 hit area check',
        'responsive check',
        'mobile review',
        'check [area] at different sizes',
      ],
      intentMarkers: ['responsive', 'breakpoint', 'touch target', 'viewport', 'validation', '40x40', 'mobile', 'tablet', 'desktop'],
      avoidCollisionWith: ['flowK_multi_lens_audit'],
      negativeFilters: ['design', 'layout', 'implement'],
    },
  },
  {
    id: 'flowN_rapid_iteration_refined',
    name: 'Rapid Iteration (Token-based)',
    description: 'Goal-driven refinement with token-based variations, success criteria framework, decision criteria. Absorbed flow13_rapid_iteration.',
    triggers: {
      patterns: [
        'iterate on [element]',
        'rapid iteration round [N]',
        'try variations of [element]',
        'token-based tweaking',
        'variation testing for [element]',
        'success criteria check',
        'iteration loop for [element]',
        'refine [element] with feedback',
        '[element] iteration round [N]',
      ],
      intentMarkers: ['iterate', 'rapid', 'round', 'variations', 'token', 'success', 'criteria', 'refine'],
      avoidCollisionWith: ['flowY_explore_discovery'],
      negativeFilters: ['explore', 'open-ended', 'discovery'],
    },
  },

  // TIER 4: SPECIAL WORKFLOWS
  {
    id: 'flowO_clone_match_special',
    name: 'Clone/Match from Reference',
    description: 'Pixel-perfect 1:1 replication - element tree, typography, interactions, exact spacing. Absorbed flow1_clone_match.',
    triggers: {
      patterns: [
        'pixel perfect match [element]',
        'clone [component] exactly',
        'steal [element] 1:1',
        'exact replication of [design]',
        'match [element] byte-for-byte',
        'identical copy [from reference]',
        'match [element] from [source]',
        'exact copy of [element]',
        '[element] identical to [source]',
        'copy [element] precisely',
      ],
      intentMarkers: ['pixel perfect', 'clone', 'steal', '1:1', 'exact', 'identical', 'byte-for-byte', 'copy precisely'],
      avoidCollisionWith: ['flowZ_design_component', 'flowG_component_implementation'],
      negativeFilters: ['design', 'component', 'approximate', 'implement', 'based on'],
    },
  },
  {
    id: 'flowP_constraint_design_special',
    name: 'Constraint-Based Design',
    description: 'Design under explicit limits - budget, scope, accessibility floor, creative problem-solving. Absorbed flow6_constraint_design.',
    triggers: {
      patterns: [
        'design under [constraint]',
        'constraint-based design for [element]',
        'design [element] with [budget/scope/limit]',
        'creative solution within [constraint]',
        'make [element] work with [rule]',
        'design given [accessibility floor]',
        'design [element] for [constraint]',
        'optimize [element] given [limit]',
        '[element] under [constraint]',
        '[element] respecting [rule]',
      ],
      intentMarkers: ['constraint', 'under', 'limit', 'budget', 'scope', 'creative', 'given', 'respecting'],
      avoidCollisionWith: ['flowZ_design_component', 'flowR_layout_optimization'],
      negativeFilters: ['improve', 'refactor', 'layout'],
    },
  },
  {
    id: 'flowQ_migration_special',
    name: 'Migration/Refactor (Special)',
    description: 'Component API refactoring - dependency mapping, pre/post signoff gates. Absorbed flow14_migration.',
    triggers: {
      patterns: [
        'migrate [component] to [new approach]',
        'breaking change in [component]',
        'refactor [component]\'s API',
        'component migration with dependencies',
        'update [component] across codebase',
        'dependency mapping for [migration]',
        'replace [old component] with [new]',
        '[component] refactor/rewrite',
        'upgrade [component]',
      ],
      intentMarkers: ['migrate', 'breaking', 'refactor', 'API', 'migration', 'dependencies', 'rewrite', 'upgrade'],
      avoidCollisionWith: ['flowR_layout_optimization'],
      negativeFilters: ['layout', 'design', 'polish', 'section'],
    },
  },

  // TIER 5: SPECIALIZED REFINEMENT (NEW - v2.1.9 coverage)
  {
    id: 'flowR_layout_optimization',
    name: 'Layout & Spacing Optimization',
    description: 'Fix layout, spacing, and visual rhythm - grid optimization, spacing ratios, visual hierarchy. Absorbed flow8_refactor_layout.',
    triggers: {
      patterns: [
        'optimize layout for [element]',
        'fix spacing in [area]',
        'improve visual rhythm',
        'layout refinement for [area]',
        'spacing grid optimization',
        'visual hierarchy adjustment',
        'fix layout issues in [area]',
        'refactor [section]',
        '[area] feels cluttered',
        'improve layout of [area]',
        'restructure [area]',
        '[area] needs better hierarchy',
        'reorganize [area]',
      ],
      intentMarkers: ['layout', 'spacing', 'rhythm', 'optimize', 'grid', 'hierarchy', 'refinement', 'refactor', 'cluttered', 'restructure', 'reorganize'],
      avoidCollisionWith: ['flowJ_tactical_polish', 'flowQ_migration_special', 'flowM_responsive_validation'],
      negativeFilters: ['design', 'implement', 'code', 'responsive', 'API', 'component migration', 'animation', 'make accessible'],
    },
  },
  {
    id: 'flowS_typography_excellence',
    name: 'Typography Excellence',
    description: 'Improves typography - font choices, hierarchy, sizing, weight, readability',
    triggers: {
      patterns: [
        'optimize typography for [area]',
        'improve [font/type] hierarchy',
        'typography excellence review',
        'typeset [area] for readability',
        'font weight and size audit',
        'text hierarchy refinement',
        'improve readability of [content]',
      ],
      intentMarkers: ['typography', 'typeset', 'font', 'hierarchy', 'readability', 'weight', 'sizing'],
      avoidCollisionWith: ['flowC_font_research', 'flowJ_tactical_polish'],
      negativeFilters: ['design', 'research', 'implement'],
    },
  },
  {
    id: 'flowT_ambitious_motion',
    name: 'Ambitious Motion & Physics',
    description: 'Push interfaces past conventional limits - shaders, spring physics, scroll-driven reveals, 60fps cinematic transitions',
    triggers: {
      patterns: [
        'push motion limits for [element]',
        'advanced animation with physics',
        'spring physics for [element]',
        'scroll-driven reveal [element]',
        'cinematic transition for [element]',
        'overdrive animations for [area]',
        '60fps advanced animation',
        'shader-based effects for [element]',
      ],
      intentMarkers: ['overdrive', 'ambitious', 'physics', 'spring', 'scroll-driven', 'cinematic', 'shader'],
      avoidCollisionWith: ['flowH_motion_integration', 'flowE_motion_patterns'],
      negativeFilters: ['research', 'basic', 'simple'],
    },
  },

  // SPECIAL: CURATE & QA
  {
    id: 'flowU_curate',
    name: 'Curate Design References',
    description: '5-step wizard for adding components and patterns to the design-references catalog',
    triggers: {
      patterns: [
        'curate [component/pattern]',
        'add [component] to catalog',
        'capture [component] reference',
        'save [design element] to references',
        'design reference for [element]',
        'add to design references',
        'catalog [component/pattern]',
      ],
      intentMarkers: ['curate', 'add reference', 'capture component', 'design reference', 'add to catalog', 'catalog'],
      avoidCollisionWith: ['flowD_reference_inspiration'],
      negativeFilters: [],
    },
  },
  {
    id: 'flowV_all_seven_qa',
    name: 'All-Seven QA Pipeline',
    description: 'End-to-end comprehensive design pipeline QA - chains all 7 tiers for verification',
    triggers: {
      patterns: [
        'all-seven QA',
        'comprehensive design QA',
        'full pipeline check',
        'end-to-end design validation',
        'QA pipeline [project/section]',
        'run all tiers',
        'complete design review',
      ],
      intentMarkers: ['all-seven', 'all seven', 'comprehensive qa', 'full pipeline', 'end-to-end', 'qa pipeline', 'all tiers'],
      avoidCollisionWith: [],
      negativeFilters: [],
    },
  },

  // TIER 6: COMPOSITION & COPY
  {
    id: 'flowW_landing_composition',
    name: 'Landing Page Composition (sections + rhythm)',
    description: 'Decide which sections a landing page needs and how to space them, register-aware (brand vs product)',
    triggers: {
      patterns: [
        'lay out a landing page',
        'compose a landing page',
        'plan the sections for [page]',
        'what sections does this landing need',
        'landing page structure',
        'section taxonomy for [register]',
      ],
      intentMarkers: ['landing', 'sections', 'compose', 'structure', 'layout-plan', 'taxonomy'],
      avoidCollisionWith: ['flowG_component_implementation', 'flowR_layout_optimization'],
      negativeFilters: ['component', 'fix', 'audit', 'critique'],
    },
  },
  {
    id: 'flowX_copywriting',
    name: 'Copywriting (per-slot draft options)',
    description: 'Generate 2-3 draft copy options per slot (hero headline, supporting line, CTA, feature title) using register + product context',
    triggers: {
      patterns: [
        'draft hero copy',
        'write copy for [section]',
        'headline options for [page]',
        'draft CTA copy',
        'copy variants for [slot]',
        'write the hero',
      ],
      intentMarkers: ['copy', 'headline', 'CTA', 'hero', 'tagline', 'draft', 'wording'],
      avoidCollisionWith: ['flowA_brand_verify', 'flowW_landing_composition'],
      negativeFilters: ['component', 'token', 'layout', 'critique'],
    },
  },

  // TIER 7: RENAMED LEGACY (T-0015) - genuinely separate flows with no lettered counterpart
  // KEEP-AS-IS rationale: flowY is the only "no success criteria, generate ideas" exploration flow.
  // flowZ is the only "design new component from scratch with QA triad" flow - distinct from
  // flowG (implement from existing design) and flowO (clone exactly).
  {
    id: 'flowY_explore_discovery',
    name: 'Exploration/Discovery Mode',
    description: 'Open-ended exploration without success criteria (renamed from flow4_explore_discovery, T-0015).',
    triggers: {
      patterns: [
        'explore [concept]',
        'what if we [tried/changed] [element]',
        'experiment with [area]',
        'discovery mode for [element]',
        'try [N] versions of [element]',
        'brainstorm [design aspect]',
        '[area] exploration',
      ],
      intentMarkers: ['explore', 'what if', 'experiment', 'discovery', 'try variations', 'brainstorm'],
      avoidCollisionWith: ['flowN_rapid_iteration_refined', 'flowR_layout_optimization'],
      negativeFilters: ['iterate', 'improve', 'round', 'success criteria'],
    },
  },
  {
    id: 'flowZ_design_component',
    name: 'Design a New Component (from scratch)',
    description: 'Create new component from scratch with QA triad (audit -> critique -> polish). Distinct from flowG (implement-from-design) and flowO (clone-exactly). Renamed from flow7_design_component, T-0015.',
    triggers: {
      patterns: [
        'design a [component]',
        'create [element]',
        'build [component]',
        'new [component]',
        'design [component] from scratch',
        'need a [component]',
        'design [element] with these states/features',
      ],
      intentMarkers: ['design', 'create', 'build', 'new', 'from scratch', 'need a'],
      avoidCollisionWith: ['flowG_component_implementation', 'flowO_clone_match_special'],
      negativeFilters: ['implement', 'from [source]', 'based on', 'clone'],
    },
  },
];

export const flowMap = new Map(flows.map((f) => [f.id, f]));

export function getFlow(flowId: FlowId): Flow | undefined {
  return flowMap.get(flowId);
}
