import { Flow, FlowId } from './types';

export const flows: Flow[] = [
  {
    id: 'flow1_clone_match',
    name: 'Clone/Match from Reference',
    description: 'Match element from design source exactly',
    triggers: {
      patterns: [
        'match [element] from [source]',
        'clone [component]',
        'steal [element] from [reference]',
        'exact copy of [element]',
        '1:1 with [design]',
        '[element] identical to [source]',
        'copy [element] precisely',
      ],
      intentMarkers: ['match', 'steal', 'clone', '1:1', 'exact', 'identical', 'copy precisely'],
      avoidCollisionWith: ['flow7_design_component', 'flow10_implement_design'],
      negativeFilters: ['build from', 'implement', 'based on'],
    },
  },
  {
    id: 'flow2_polish_enhance',
    name: 'Polish/Enhance Interaction',
    description: 'Add feeling, animation, and microinteractions',
    triggers: {
      patterns: [
        'add feeling to [element]',
        'make this feel better',
        'enhance interaction on [element]',
        'polish [element]',
        '[element] needs more life',
        'make [element] less janky',
        'improve the experience of [element]',
        'add micro[interaction/animation]',
      ],
      intentMarkers: ['feel', 'polish', 'experience', 'life', 'janky', 'microinteraction', 'animation'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow9_accessible'],
      negativeFilters: ['improve layout', 'make accessible', 'hierarchy'],
    },
  },
  {
    id: 'flow3_audit_page',
    name: 'Audit Page/Section',
    description: 'Report issues without suggesting fixes',
    triggers: {
      patterns: [
        'audit [page/section]',
        'review [area] for issues',
        'QA check [area]',
        'what\'s wrong with [page]',
        'find issues on [page]',
        'scan [area] for problems',
        'technical audit of [area]',
      ],
      intentMarkers: ['audit', 'review for issues', 'QA check', 'find issues', 'scan', 'what\'s wrong'],
      avoidCollisionWith: ['flow5_review_qa', 'flow9_accessible'],
      negativeFilters: ['code review', 'comprehensive', 'make accessible'],
    },
  },
  {
    id: 'flow4_explore_discovery',
    name: 'Exploration/Discovery Mode',
    description: 'Open-ended exploration without success criteria',
    triggers: {
      patterns: [
        'explore [concept]',
        'what if we [tried/changed] [element]',
        'experiment with [area]',
        'discovery mode for [element]',
        'try [N] versions of [element]',
        'brainstorm [design aspect]',
        '[area] exploration',
      ],
      intentMarkers: ['explore', 'what if', 'experiment', 'discovery', 'try variations', 'brainstorm'],
      avoidCollisionWith: ['flow13_rapid_iteration', 'flow8_refactor_layout'],
      negativeFilters: ['iterate', 'improve', 'round', 'success criteria'],
    },
  },
  {
    id: 'flow5_review_qa',
    name: 'Review/QA Mode',
    description: 'Comprehensive multi-lens check with fix intent',
    triggers: {
      patterns: [
        'review this PR',
        'code review [area]',
        'QA this',
        'review [component] for quality',
        'do a full review',
        'comprehensive check of [area]',
        'check for design/performance/a11y issues',
      ],
      intentMarkers: ['review', 'code review', 'comprehensive check', 'for quality', 'QA this'],
      avoidCollisionWith: ['flow3_audit_page', 'flow8_refactor_layout'],
      negativeFilters: ['audit', 'improve', 'report only'],
    },
  },
  {
    id: 'flow6_constraint_design',
    name: 'Constraint-Based Design',
    description: 'Design under explicit constraints or limits',
    triggers: {
      patterns: [
        'design [element] for [constraint]',
        'design with [constraint]',
        'optimize [element] given [limit]',
        '[element] under [constraint]',
        'design [element] at [constraint]',
        'make [element] work with [constraint]',
        '[element] respecting [rule]',
      ],
      intentMarkers: ['design for', 'design with', 'optimize given', 'under', 'at', 'respecting', 'constraint'],
      avoidCollisionWith: ['flow7_design_component', 'flow8_refactor_layout'],
      negativeFilters: ['improve layout', 'refactor'],
    },
  },
  {
    id: 'flow7_design_component',
    name: 'Design a New Component',
    description: 'Create new component from scratch',
    triggers: {
      patterns: [
        'design a [component]',
        'create [element]',
        'build [component]',
        'new [component]',
        'design [component] from scratch',
        'need a [component]',
        'design [element] with these states/features',
      ],
      intentMarkers: ['design', 'create', 'build', 'new', 'from scratch', 'need a'],
      avoidCollisionWith: ['flow10_implement_design', 'flow1_clone_match'],
      negativeFilters: ['implement', 'from [source]', 'based on', 'clone'],
    },
  },
  {
    id: 'flow8_refactor_layout',
    name: 'Refactor/Improve Section',
    description: 'Improve structure, hierarchy, and whitespace',
    triggers: {
      patterns: [
        'refactor [section]',
        '[area] feels cluttered',
        'improve layout of [area]',
        'restructure [area]',
        '[area] needs better hierarchy',
        'reorganize [area]',
        'make [area] clearer',
        'layout improvements for [area]',
      ],
      intentMarkers: ['refactor', 'cluttered', 'hierarchy', 'layout', 'restructure', 'reorganize', 'clearer'],
      avoidCollisionWith: ['flow2_polish_enhance', 'flow14_migration', 'flow12_responsive_review'],
      negativeFilters: ['make accessible', 'responsive', 'API', 'component migration', 'animation'],
    },
  },
  {
    id: 'flow9_accessible',
    name: 'Make Accessible',
    description: 'Ensure WCAG compliance and accessibility standards',
    triggers: {
      patterns: [
        'make [area] accessible',
        'a11y audit [area]',
        'accessibility check',
        'screen reader test [area]',
        'WCAG [AA/AAA] [area]',
        'improve a11y of [area]',
        '[area] needs keyboard navigation',
        'fix accessibility issues',
      ],
      intentMarkers: ['accessible', 'a11y', 'screen reader', 'WCAG', 'keyboard navigation', 'accessibility'],
      avoidCollisionWith: ['flow3_audit_page', 'flow8_refactor_layout'],
      negativeFilters: ['audit [generic]', 'improve [generic]', 'layout'],
    },
  },
  {
    id: 'flow10_implement_design',
    name: 'Implement from Design',
    description: 'Code implementation from existing design reference',
    triggers: {
      patterns: [
        'implement [component]',
        'code this design',
        'build from [Figma/reference]',
        '[component] from [design source]',
        'code [element] from [reference]',
        'build [component] based on [design]',
        'implement design for [element]',
      ],
      intentMarkers: ['implement', 'code', 'build from', 'build based on', 'from [source]'],
      avoidCollisionWith: ['flow7_design_component', 'flow1_clone_match'],
      negativeFilters: ['design', 'clone', 'exact pixel'],
    },
  },
  {
    id: 'flow11_extract_tokens',
    name: 'Extract Tokens/Create Variant',
    description: 'Extract repeated patterns into reusable tokens',
    triggers: {
      patterns: [
        'extract [pattern]',
        'create a token for [pattern]',
        'make [pattern] reusable',
        'define [variant]',
        'standardize [pattern]',
        '[pattern] keeps repeating, extract it',
        'convert [pattern] to token',
      ],
      intentMarkers: ['extract', 'token', 'reusable', 'standardize', 'variant', 'repeating'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow7_design_component'],
      negativeFilters: ['refactor', 'design', 'layout'],
    },
  },
  {
    id: 'flow12_responsive_review',
    name: 'Responsive Design Review',
    description: 'Test across screen sizes and breakpoints',
    triggers: {
      patterns: [
        'responsive check',
        'mobile review',
        'test breakpoints',
        'responsive [area]',
        'tablet/mobile/desktop testing',
        'breakpoint validation',
        'check [area] at different sizes',
      ],
      intentMarkers: ['responsive', 'mobile', 'breakpoint', 'sizes', 'tablet', 'desktop'],
      avoidCollisionWith: ['flow8_refactor_layout'],
      negativeFilters: ['hierarchy', 'layout', 'structure'],
    },
  },
  {
    id: 'flow13_rapid_iteration',
    name: 'Rapid Iteration Cycle',
    description: 'Goal-driven refinement with success criteria',
    triggers: {
      patterns: [
        'iterate on [element]',
        'try variations',
        'rapid iteration on [element]',
        'cycle through ideas',
        'refine [element] with feedback',
        '[element] iteration round [N]',
        'quick variations of [element]',
      ],
      intentMarkers: ['iterate', 'try variations', 'cycle through', 'refine', 'round', 'quick variations'],
      avoidCollisionWith: ['flow4_explore_discovery', 'flow8_refactor_layout'],
      negativeFilters: ['explore', 'open-ended', 'discovery'],
    },
  },
  {
    id: 'flow14_migration',
    name: 'Migration/Refactor Existing Component',
    description: 'API change or component replacement with dependencies',
    triggers: {
      patterns: [
        'migrate [component] to [new approach]',
        'update [component]',
        'replace [old component] with [new]',
        '[component] refactor/rewrite',
        'upgrade [component]',
        'refactor [component]\'s API',
        'breaking change in [component]',
      ],
      intentMarkers: ['migrate', 'update', 'replace', 'refactor', 'rewrite', 'upgrade', 'API', 'breaking change'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow7_design_component'],
      negativeFilters: ['layout', 'design', 'section'],
    },
  },
];

export const flowMap = new Map(flows.map((f) => [f.id, f]));

export function getFlow(flowId: FlowId): Flow | undefined {
  return flowMap.get(flowId);
}
