import { Flow, FlowId } from './types';

export const flows: Flow[] = [
  // TIER 1: STRATEGY/RESEARCH
  {
    id: 'flowA_brand_verify',
    name: 'Brand/PRODUCT.md Verification',
    description: 'Verify project has valid brand register before design work',
    triggers: {
      patterns: [
        'check brand[s]',
        'verify [brand/product] register',
        'validate brand',
        'do i have product.md',
        'check project setup',
        'verify design foundation',
        'initialize brand',
      ],
      intentMarkers: ['brand', 'verify', 'register', 'product.md', 'setup', 'foundation', 'initialize'],
      avoidCollisionWith: ['flowB_component_research', 'flowE_motion_patterns'],
      negativeFilters: ['design', 'component', 'implement'],
    },
  },
  {
    id: 'flowB_component_research',
    name: 'Component Research (component.gallery)',
    description: 'Research component patterns and implementations (60 types, 95 systems)',
    triggers: {
      patterns: [
        'research [component/pattern]',
        'find [component] examples',
        'component gallery search [pattern]',
        '[component] patterns',
        'what components exist for [use case]',
        '[component] accessibility baseline',
        'component recommendations for [constraint]',
      ],
      intentMarkers: ['research', 'component', 'gallery', 'examples', 'patterns', 'baseline', 'recommendations'],
      avoidCollisionWith: ['flowC_font_research', 'flow7_design_component'],
      negativeFilters: ['design', 'implement', 'build'],
    },
  },
  {
    id: 'flowC_font_research',
    name: 'Font Research (fontshare.com)',
    description: 'Research typefaces and pairing against brand personality',
    triggers: {
      patterns: [
        'research fonts',
        'find typeface for [brand/use case]',
        'fontshare search [style]',
        'font pairing for [brand]',
        '[font] weights and licensing',
        'typography research for [project]',
        'what fonts match [personality]',
      ],
      intentMarkers: ['font', 'typeface', 'fontshare', 'pairing', 'weights', 'typography', 'licensing'],
      avoidCollisionWith: ['flowD_reference_inspiration', 'flowB_component_research'],
      negativeFilters: ['design', 'implement', 'set font'],
    },
  },
  {
    id: 'flowD_reference_inspiration',
    name: 'Reference/Inspiration Search (design-references)',
    description: 'Search personal design reference catalog for patterns and inspiration',
    triggers: {
      patterns: [
        'search references for [pattern]',
        'curate [design aspect]',
        'find inspiration for [element]',
        'reference search [concept]',
        'design patterns catalog [query]',
        'show me examples of [style]',
        'inspiration for [design task]',
      ],
      intentMarkers: ['reference', 'inspiration', 'curate', 'search', 'catalog', 'examples', 'patterns'],
      avoidCollisionWith: ['flowE_motion_patterns', 'flow7_design_component'],
      negativeFilters: ['implement', 'design', 'build'],
    },
  },
  {
    id: 'flowE_motion_patterns',
    name: 'Motion Pattern Library (GSAP/Lenis)',
    description: 'Research motion patterns and animation techniques (tweens, ScrollTrigger, Flip, SplitText, DrawSVG)',
    triggers: {
      patterns: [
        'motion patterns for [element]',
        'GSAP examples for [animation]',
        'scrolltrigger pattern [concept]',
        'animation library [effect]',
        'motion research for [interaction]',
        'smooth scroll patterns',
        'flip animation examples',
      ],
      intentMarkers: ['motion', 'GSAP', 'animation', 'scroll', 'pattern', 'library', 'effect'],
      avoidCollisionWith: ['flowH_motion_integration', 'flowB_component_research'],
      negativeFilters: ['implement', 'build', 'code'],
    },
  },

  // TIER 2: EXECUTION
  {
    id: 'flowF_design_tokens',
    name: 'Design System Tokens (DESIGN.md)',
    description: 'Full DESIGN.md workflow - extract, manage, lint tokens (google-labs-code spec)',
    triggers: {
      patterns: [
        'extract design tokens',
        'create design.md',
        'manage design tokens',
        'token extraction from [design]',
        'validate tokens against [standard]',
        'lint design.md',
        'token consistency check',
      ],
      intentMarkers: ['token', 'design.md', 'extract', 'manage', 'lint', 'consistency', 'validate'],
      avoidCollisionWith: ['flowG_component_implementation', 'flow11_extract_tokens'],
      negativeFilters: ['implement', 'build', 'component'],
    },
  },
  {
    id: 'flowG_component_implementation',
    name: 'Component Implementation',
    description: 'Map design spec to implementation, wire variants, states, responsive behavior (replaces flow10)',
    triggers: {
      patterns: [
        'implement [component] from design',
        'code component [name]',
        'build [component] with states',
        'component implementation for [design]',
        'wire variants of [component]',
        'make [component] responsive',
        'component implementation checklist',
      ],
      intentMarkers: ['implement', 'component', 'code', 'variants', 'states', 'responsive', 'wire'],
      avoidCollisionWith: ['flow10_implement_design', 'flow7_design_component'],
      negativeFilters: ['design', 'clone', 'exact'],
    },
  },
  {
    id: 'flowH_motion_integration',
    name: 'Motion Integration (GSAP/Lenis)',
    description: 'Implement production-ready motion - tweens, ScrollTrigger, Flip, SplitText, DrawSVG',
    triggers: {
      patterns: [
        'add motion to [element]',
        'implement GSAP animation',
        'scrolltrigger for [element]',
        'motion implementation for [interaction]',
        'integrate smooth scroll',
        'animate [element] with DrawSVG',
        'production motion code',
      ],
      intentMarkers: ['motion', 'animation', 'GSAP', 'scroll', 'tweens', 'implement', 'integrate'],
      avoidCollisionWith: ['flowE_motion_patterns', 'flow2_polish_enhance'],
      negativeFilters: ['research', 'pattern', 'example'],
    },
  },
  {
    id: 'flowI_accessibility',
    name: 'Accessibility Compliance (WCAG 2.1 AA)',
    description: 'WCAG 2.1 AA validation, screen reader testing, severity prioritization (same as flow9)',
    triggers: {
      patterns: [
        'make [area] accessible',
        'a11y audit [area]',
        'accessibility check [element]',
        'screen reader test [area]',
        'WCAG [AA/AAA] [area]',
        'fix a11y issues',
        'semantic HTML validation',
      ],
      intentMarkers: ['accessible', 'a11y', 'screen reader', 'WCAG', 'semantic', 'keyboard', 'aria'],
      avoidCollisionWith: ['flow9_accessible', 'flowK_multi_lens_audit'],
      negativeFilters: ['audit [generic]', 'improve [generic]', 'layout'],
    },
  },

  // TIER 3: POLISH/QA
  {
    id: 'flowJ_tactical_polish',
    name: '16-Point Tactical Polish',
    description: 'All make-interfaces-feel-better rules: concentric radius, optical alignment, shadows, animations, hit areas, icons, numbers, wrapping, outlines, scale, motion, transitions, will-change',
    triggers: {
      patterns: [
        'polish [element]',
        'make this feel better',
        'tactical refinement of [element]',
        'apply polish rules',
        '[element] 16-point check',
        'interface feel improvement',
        'micro-interaction polish',
        'apply make-interfaces-feel-better',
      ],
      intentMarkers: ['polish', 'feel better', 'tactical', 'refinement', '16-point', 'micro-interaction'],
      avoidCollisionWith: ['flow2_polish_enhance', 'flowK_multi_lens_audit'],
      negativeFilters: ['audit', 'design', 'implement', 'layout'],
    },
  },
  {
    id: 'flowK_multi_lens_audit',
    name: 'Multi-Lens Audit (5 dimensions)',
    description: 'Technical scan - accessibility, performance, theming, responsive, anti-patterns (addresses all Critical/High findings)',
    triggers: {
      patterns: [
        'multi-lens audit [area]',
        'technical audit [area]',
        '5-dimension audit',
        'comprehensive technical check',
        'find all issues in [area]',
        'detect anti-patterns in [area]',
        'performance/a11y/responsive audit',
      ],
      intentMarkers: ['multi-lens', 'audit', 'technical', '5-dimension', 'anti-pattern', 'comprehensive'],
      avoidCollisionWith: ['flow3_audit_page', 'flowI_accessibility'],
      negativeFilters: ['design', 'polish', 'improvement'],
    },
  },
  {
    id: 'flowL_design_critique',
    name: 'Design Critique (Nielsen heuristics)',
    description: 'Independent design review - Nielsen heuristics, AI-slop detection, cognitive load, emotional journey',
    triggers: {
      patterns: [
        'design critique [area]',
        'review [design] for quality',
        'Nielsen heuristics check',
        'ai-slop detection for [area]',
        'cognitive load assessment',
        'emotional journey mapping',
        'independent design review',
      ],
      intentMarkers: ['critique', 'review', 'Nielsen', 'heuristics', 'cognitive', 'emotional', 'quality'],
      avoidCollisionWith: ['flow5_review_qa', 'flowK_multi_lens_audit'],
      negativeFilters: ['audit', 'implement', 'code'],
    },
  },
  {
    id: 'flowM_responsive_validation',
    name: 'Responsive Design Validation',
    description: 'Breakpoint testing (from DESIGN.md), touch target verification (40x40px minimum), viewport behavior',
    triggers: {
      patterns: [
        'responsive validation [area]',
        'breakpoint test [area]',
        'touch target check',
        'viewport behavior test',
        'mobile/tablet/desktop validation',
        'responsive review [area]',
        '40x40 hit area check',
      ],
      intentMarkers: ['responsive', 'breakpoint', 'touch target', 'viewport', 'validation', '40x40'],
      avoidCollisionWith: ['flow12_responsive_review', 'flowK_multi_lens_audit'],
      negativeFilters: ['design', 'layout', 'implement'],
    },
  },
  {
    id: 'flowN_rapid_iteration_refined',
    name: 'Rapid Iteration (Token-based)',
    description: 'Goal-driven refinement with token-based variations, success criteria framework, decision criteria',
    triggers: {
      patterns: [
        'iterate on [element]',
        'rapid iteration round [N]',
        'try variations of [element]',
        'token-based tweaking',
        'variation testing for [element]',
        'success criteria check',
        'iteration loop for [element]',
      ],
      intentMarkers: ['iterate', 'rapid', 'round', 'variations', 'token', 'success', 'criteria'],
      avoidCollisionWith: ['flow13_rapid_iteration', 'flow4_explore_discovery'],
      negativeFilters: ['explore', 'open-ended', 'discovery'],
    },
  },

  // TIER 4: SPECIAL WORKFLOWS
  {
    id: 'flowO_clone_match_special',
    name: 'Clone/Match from Reference (Special)',
    description: 'Pixel-perfect 1:1 replication - element tree, typography, interactions, exact spacing',
    triggers: {
      patterns: [
        'pixel perfect match [element]',
        'clone [component] exactly',
        'steal [element] 1:1',
        'exact replication of [design]',
        'match [element] byte-for-byte',
        'identical copy [from reference]',
      ],
      intentMarkers: ['pixel perfect', 'clone', 'steal', '1:1', 'exact', 'identical', 'byte-for-byte'],
      avoidCollisionWith: ['flow1_clone_match', 'flow7_design_component'],
      negativeFilters: ['design', 'component', 'approximate'],
    },
  },
  {
    id: 'flowP_constraint_design_special',
    name: 'Constraint-Based Design (Special)',
    description: 'Design under explicit limits - budget, scope, accessibility floor, creative problem-solving',
    triggers: {
      patterns: [
        'design under [constraint]',
        'constraint-based design for [element]',
        'design [element] with [budget/scope/limit]',
        'creative solution within [constraint]',
        'make [element] work with [rule]',
        'design given [accessibility floor]',
      ],
      intentMarkers: ['constraint', 'under', 'limit', 'budget', 'scope', 'creative', 'given'],
      avoidCollisionWith: ['flow6_constraint_design', 'flow7_design_component'],
      negativeFilters: ['improve', 'refactor', 'layout'],
    },
  },
  {
    id: 'flowQ_migration_special',
    name: 'Migration/Refactor (Special)',
    description: 'Component API refactoring - dependency mapping, pre/post signoff gates',
    triggers: {
      patterns: [
        'migrate [component] to [new approach]',
        'breaking change in [component]',
        'refactor [component]\'s API',
        'component migration with dependencies',
        'update [component] across codebase',
        'dependency mapping for [migration]',
      ],
      intentMarkers: ['migrate', 'breaking', 'refactor', 'API', 'migration', 'dependencies'],
      avoidCollisionWith: ['flow14_migration', 'flow8_refactor_layout'],
      negativeFilters: ['layout', 'design', 'polish'],
    },
  },

  // TIER 5: SPECIALIZED REFINEMENT (NEW - v2.1.9 coverage)
  {
    id: 'flowR_layout_optimization',
    name: 'Layout & Spacing Optimization',
    description: 'Fix layout, spacing, and visual rhythm - grid optimization, spacing ratios, visual hierarchy',
    triggers: {
      patterns: [
        'optimize layout for [element]',
        'fix spacing in [area]',
        'improve visual rhythm',
        'layout refinement for [area]',
        'spacing grid optimization',
        'visual hierarchy adjustment',
        'fix layout issues in [area]',
      ],
      intentMarkers: ['layout', 'spacing', 'rhythm', 'optimize', 'grid', 'hierarchy', 'refinement'],
      avoidCollisionWith: ['flowJ_tactical_polish', 'flow8_refactor_layout'],
      negativeFilters: ['design', 'implement', 'code', 'responsive'],
    },
  },
  {
    id: 'flowS_typography_excellence',
    name: 'Typography Excellence',
    description: 'Improves typography - font choices, hierarchy, sizing, weight, readability',
    triggers: {
      patterns: [
        'optimize typography for [area]',
        'improve [font/type] hierarchy',
        'typography excellence review',
        'typeset [area] for readability',
        'font weight and size audit',
        'text hierarchy refinement',
        'improve readability of [content]',
      ],
      intentMarkers: ['typography', 'typeset', 'font', 'hierarchy', 'readability', 'weight', 'sizing'],
      avoidCollisionWith: ['flowC_font_research', 'flowJ_tactical_polish'],
      negativeFilters: ['design', 'research', 'implement'],
    },
  },
  {
    id: 'flowT_ambitious_motion',
    name: 'Ambitious Motion & Physics',
    description: 'Push interfaces past conventional limits - shaders, spring physics, scroll-driven reveals, 60fps cinematic transitions',
    triggers: {
      patterns: [
        'push motion limits for [element]',
        'advanced animation with physics',
        'spring physics for [element]',
        'scroll-driven reveal [element]',
        'cinematic transition for [element]',
        'overdrive animations for [area]',
        '60fps advanced animation',
        'shader-based effects for [element]',
      ],
      intentMarkers: ['overdrive', 'ambitious', 'physics', 'spring', 'scroll-driven', 'cinematic', 'shader'],
      avoidCollisionWith: ['flowH_motion_integration', 'flowE_motion_patterns'],
      negativeFilters: ['research', 'basic', 'simple'],
    },
  },

  // Existing flows (legacy mapping)
  {
    id: 'flow1_clone_match',
    name: 'Clone/Match from Reference',
    description: 'Match element from design source exactly',
    triggers: {
      patterns: [
        'match [element] from [source]',
        'clone [component]',
        'steal [element] from [reference]',
        'exact copy of [element]',
        '1:1 with [design]',
        '[element] identical to [source]',
        'copy [element] precisely',
      ],
      intentMarkers: ['match', 'steal', 'clone', '1:1', 'exact', 'identical', 'copy precisely'],
      avoidCollisionWith: ['flow7_design_component', 'flow10_implement_design'],
      negativeFilters: ['build from', 'implement', 'based on'],
    },
  },
  {
    id: 'flow2_polish_enhance',
    name: 'Polish/Enhance Interaction',
    description: 'Add feeling, animation, and microinteractions',
    triggers: {
      patterns: [
        'add feeling to [element]',
        'make this feel better',
        'enhance interaction on [element]',
        'polish [element]',
        '[element] needs more life',
        'make [element] less janky',
        'improve the experience of [element]',
        'add micro[interaction/animation]',
      ],
      intentMarkers: ['feel', 'polish', 'experience', 'life', 'janky', 'microinteraction', 'animation'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow9_accessible'],
      negativeFilters: ['improve layout', 'make accessible', 'hierarchy'],
    },
  },
  {
    id: 'flow3_audit_page',
    name: 'Audit Page/Section',
    description: 'Report issues without suggesting fixes',
    triggers: {
      patterns: [
        'audit [page/section]',
        'review [area] for issues',
        'QA check [area]',
        'what\'s wrong with [page]',
        'find issues on [page]',
        'scan [area] for problems',
        'technical audit of [area]',
      ],
      intentMarkers: ['audit', 'review for issues', 'QA check', 'find issues', 'scan', 'what\'s wrong'],
      avoidCollisionWith: ['flow5_review_qa', 'flow9_accessible'],
      negativeFilters: ['code review', 'comprehensive', 'make accessible'],
    },
  },
  {
    id: 'flow4_explore_discovery',
    name: 'Exploration/Discovery Mode',
    description: 'Open-ended exploration without success criteria',
    triggers: {
      patterns: [
        'explore [concept]',
        'what if we [tried/changed] [element]',
        'experiment with [area]',
        'discovery mode for [element]',
        'try [N] versions of [element]',
        'brainstorm [design aspect]',
        '[area] exploration',
      ],
      intentMarkers: ['explore', 'what if', 'experiment', 'discovery', 'try variations', 'brainstorm'],
      avoidCollisionWith: ['flow13_rapid_iteration', 'flow8_refactor_layout'],
      negativeFilters: ['iterate', 'improve', 'round', 'success criteria'],
    },
  },
  {
    id: 'flow5_review_qa',
    name: 'Review/QA Mode',
    description: 'Comprehensive multi-lens check with fix intent',
    triggers: {
      patterns: [
        'review this PR',
        'code review [area]',
        'QA this',
        'review [component] for quality',
        'do a full review',
        'comprehensive check of [area]',
        'check for design/performance/a11y issues',
      ],
      intentMarkers: ['review', 'code review', 'comprehensive check', 'for quality', 'QA this'],
      avoidCollisionWith: ['flow3_audit_page', 'flow8_refactor_layout'],
      negativeFilters: ['audit', 'improve', 'report only'],
    },
  },
  {
    id: 'flow6_constraint_design',
    name: 'Constraint-Based Design',
    description: 'Design under explicit constraints or limits',
    triggers: {
      patterns: [
        'design [element] for [constraint]',
        'design with [constraint]',
        'optimize [element] given [limit]',
        '[element] under [constraint]',
        'design [element] at [constraint]',
        'make [element] work with [constraint]',
        '[element] respecting [rule]',
      ],
      intentMarkers: ['design for', 'design with', 'optimize given', 'under', 'at', 'respecting', 'constraint'],
      avoidCollisionWith: ['flow7_design_component', 'flow8_refactor_layout'],
      negativeFilters: ['improve layout', 'refactor'],
    },
  },
  {
    id: 'flow7_design_component',
    name: 'Design a New Component',
    description: 'Create new component from scratch',
    triggers: {
      patterns: [
        'design a [component]',
        'create [element]',
        'build [component]',
        'new [component]',
        'design [component] from scratch',
        'need a [component]',
        'design [element] with these states/features',
      ],
      intentMarkers: ['design', 'create', 'build', 'new', 'from scratch', 'need a'],
      avoidCollisionWith: ['flow10_implement_design', 'flow1_clone_match'],
      negativeFilters: ['implement', 'from [source]', 'based on', 'clone'],
    },
  },
  {
    id: 'flow8_refactor_layout',
    name: 'Refactor/Improve Section',
    description: 'Improve structure, hierarchy, and whitespace',
    triggers: {
      patterns: [
        'refactor [section]',
        '[area] feels cluttered',
        'improve layout of [area]',
        'restructure [area]',
        '[area] needs better hierarchy',
        'reorganize [area]',
        'make [area] clearer',
        'layout improvements for [area]',
      ],
      intentMarkers: ['refactor', 'cluttered', 'hierarchy', 'layout', 'restructure', 'reorganize', 'clearer'],
      avoidCollisionWith: ['flow2_polish_enhance', 'flow14_migration', 'flow12_responsive_review'],
      negativeFilters: ['make accessible', 'responsive', 'API', 'component migration', 'animation'],
    },
  },
  {
    id: 'flow9_accessible',
    name: 'Make Accessible',
    description: 'Ensure WCAG compliance and accessibility standards',
    triggers: {
      patterns: [
        'make [area] accessible',
        'a11y audit [area]',
        'accessibility check',
        'screen reader test [area]',
        'WCAG [AA/AAA] [area]',
        'improve a11y of [area]',
        '[area] needs keyboard navigation',
        'fix accessibility issues',
      ],
      intentMarkers: ['accessible', 'a11y', 'screen reader', 'WCAG', 'keyboard navigation', 'accessibility'],
      avoidCollisionWith: ['flow3_audit_page', 'flow8_refactor_layout'],
      negativeFilters: ['audit [generic]', 'improve [generic]', 'layout'],
    },
  },
  {
    id: 'flow10_implement_design',
    name: 'Implement from Design',
    description: 'Code implementation from existing design reference',
    triggers: {
      patterns: [
        'implement [component]',
        'code this design',
        'build from [Figma/reference]',
        '[component] from [design source]',
        'code [element] from [reference]',
        'build [component] based on [design]',
        'implement design for [element]',
      ],
      intentMarkers: ['implement', 'code', 'build from', 'build based on', 'from [source]'],
      avoidCollisionWith: ['flow7_design_component', 'flow1_clone_match'],
      negativeFilters: ['design', 'clone', 'exact pixel'],
    },
  },
  {
    id: 'flow11_extract_tokens',
    name: 'Extract Tokens/Create Variant',
    description: 'Extract repeated patterns into reusable tokens',
    triggers: {
      patterns: [
        'extract [pattern]',
        'create a token for [pattern]',
        'make [pattern] reusable',
        'define [variant]',
        'standardize [pattern]',
        '[pattern] keeps repeating, extract it',
        'convert [pattern] to token',
      ],
      intentMarkers: ['extract', 'token', 'reusable', 'standardize', 'variant', 'repeating'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow7_design_component'],
      negativeFilters: ['refactor', 'design', 'layout'],
    },
  },
  {
    id: 'flow12_responsive_review',
    name: 'Responsive Design Review',
    description: 'Test across screen sizes and breakpoints',
    triggers: {
      patterns: [
        'responsive check',
        'mobile review',
        'test breakpoints',
        'responsive [area]',
        'tablet/mobile/desktop testing',
        'breakpoint validation',
        'check [area] at different sizes',
      ],
      intentMarkers: ['responsive', 'mobile', 'breakpoint', 'sizes', 'tablet', 'desktop'],
      avoidCollisionWith: ['flow8_refactor_layout'],
      negativeFilters: ['hierarchy', 'layout', 'structure'],
    },
  },
  {
    id: 'flow13_rapid_iteration',
    name: 'Rapid Iteration Cycle',
    description: 'Goal-driven refinement with success criteria',
    triggers: {
      patterns: [
        'iterate on [element]',
        'try variations',
        'rapid iteration on [element]',
        'cycle through ideas',
        'refine [element] with feedback',
        '[element] iteration round [N]',
        'quick variations of [element]',
      ],
      intentMarkers: ['iterate', 'try variations', 'cycle through', 'refine', 'round', 'quick variations'],
      avoidCollisionWith: ['flow4_explore_discovery', 'flow8_refactor_layout'],
      negativeFilters: ['explore', 'open-ended', 'discovery'],
    },
  },
  {
    id: 'flow14_migration',
    name: 'Migration/Refactor Existing Component',
    description: 'API change or component replacement with dependencies',
    triggers: {
      patterns: [
        'migrate [component] to [new approach]',
        'update [component]',
        'replace [old component] with [new]',
        '[component] refactor/rewrite',
        'upgrade [component]',
        'refactor [component]\'s API',
        'breaking change in [component]',
      ],
      intentMarkers: ['migrate', 'update', 'replace', 'refactor', 'rewrite', 'upgrade', 'API', 'breaking change'],
      avoidCollisionWith: ['flow8_refactor_layout', 'flow7_design_component'],
      negativeFilters: ['layout', 'design', 'section'],
    },
  },
  // SPECIAL: CURATE & QA
  {
    id: 'flowU_curate',
    name: 'Curate Design References',
    description: '5-step wizard for adding components and patterns to the design-references catalog',
    triggers: {
      patterns: [
        'curate [component/pattern]',
        'add [component] to catalog',
        'capture [component] reference',
        'save [design element] to references',
        'design reference for [element]',
        'add to design references',
        'catalog [component/pattern]',
      ],
      intentMarkers: ['curate', 'add reference', 'capture component', 'design reference', 'add to catalog', 'catalog'],
      avoidCollisionWith: ['flowD_reference_inspiration'],
      negativeFilters: [],
    },
  },
  {
    id: 'flowV_all_seven_qa',
    name: 'All-Seven QA Pipeline',
    description: 'End-to-end comprehensive design pipeline QA - chains all 7 tiers for verification',
    triggers: {
      patterns: [
        'all-seven QA',
        'comprehensive design QA',
        'full pipeline check',
        'end-to-end design validation',
        'QA pipeline [project/section]',
        'run all tiers',
        'complete design review',
      ],
      intentMarkers: ['all-seven', 'all seven', 'comprehensive qa', 'full pipeline', 'end-to-end', 'qa pipeline', 'all tiers'],
      avoidCollisionWith: [],
      negativeFilters: [],
    },
  },
  // TIER 6: COMPOSITION & COPY
  {
    id: 'flowW_landing_composition',
    name: 'Landing Page Composition (sections + rhythm)',
    description: 'Decide which sections a landing page needs and how to space them, register-aware (brand vs product)',
    triggers: {
      patterns: [
        'lay out a landing page',
        'compose a landing page',
        'plan the sections for [page]',
        'what sections does this landing need',
        'landing page structure',
        'section taxonomy for [register]',
      ],
      intentMarkers: ['landing', 'sections', 'compose', 'structure', 'layout-plan', 'taxonomy'],
      avoidCollisionWith: ['flowG_component_implementation', 'flow8_refactor_layout'],
      negativeFilters: ['component', 'fix', 'audit', 'critique'],
    },
  },
  {
    id: 'flowX_copywriting',
    name: 'Copywriting (per-slot draft options)',
    description: 'Generate 2-3 draft copy options per slot (hero headline, supporting line, CTA, feature title) using register + product context',
    triggers: {
      patterns: [
        'draft hero copy',
        'write copy for [section]',
        'headline options for [page]',
        'draft CTA copy',
        'copy variants for [slot]',
        'write the hero',
      ],
      intentMarkers: ['copy', 'headline', 'CTA', 'hero', 'tagline', 'draft', 'wording'],
      avoidCollisionWith: ['flowA_brand_verify', 'flowW_landing_composition'],
      negativeFilters: ['component', 'token', 'layout', 'critique'],
    },
  },
];

export const flowMap = new Map(flows.map((f) => [f.id, f]));

export function getFlow(flowId: FlowId): Flow | undefined {
  return flowMap.get(flowId);
}
