// sidecoach/src/product-rule-registry.ts
import type { ProductRuleDefinition } from './product-rule-types';
import { supportedKindsFor } from './validators/source-support-matrix';

// The shared HTML-structural-detector override reason (absolute-ban-detector.ts:19-21).
// Both heuristic markup bans (identical-card-grids, hero-metric-template) cite it.
const STRUCTURAL_OVERRIDE_REASON =
  'HTML-structural detector flags pattern shapes, not certainties; false positives are possible (absolute-ban-detector.ts:19-21). Demoted from the table default major to non-blocking minor.';

// P4a-2 partial-static slice: 30 canonical rules across four owners. supportedSourceKinds
// is sourced from the ONE shared matrix (supportedKindsFor) so registry generation and
// project collection cannot drift. Browser-evidence rules (computed-style/dom/contrast)
// are owned-but-non-required and surface inconclusive until a browser collector (P4b).
export const RULES: ProductRuleDefinition[] = [
  // ====================== owner polish-standard (19) ======================
  {
    ruleId: 'polish.scale-on-press',
    sourceRuleAliases: ['polish-standard:1', 'POLISH_001'],
    canonicalRuleKey: 'polish/scale-on-press',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'high',
    severity: 'major',
    findingClass: 'polish',
    registryScope: 'polished-press-feedback',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.concentric-radius',
    sourceRuleAliases: ['polish-standard:2', 'POLISH_002'],
    canonicalRuleKey: 'polish/concentric-radius',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-radius-concentricity',
    evidenceRequirements: ['computed-style'],
    supportedSourceKinds: supportedKindsFor('computed-style'),
    scope: 'component',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'inconclusive',
  },
  {
    ruleId: 'polish.icon-swap-compound',
    sourceRuleAliases: ['polish-standard:3', 'POLISH_003'],
    canonicalRuleKey: 'polish/icon-swap-compound',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-icon-transition',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.image-outline-neutral',
    sourceRuleAliases: ['polish-standard:4', 'POLISH_004'],
    canonicalRuleKey: 'polish/image-outline-neutral',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'low',
    severity: 'advisory',
    findingClass: 'polish',
    registryScope: 'polished-image-outline',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.no-transition-all',
    sourceRuleAliases: ['polish-standard:6', 'POLISH_006'],
    canonicalRuleKey: 'polish/no-transition-all',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'high',
    severity: 'major',
    findingClass: 'polish',
    registryScope: 'polished-explicit-transition',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.tabular-nums',
    sourceRuleAliases: ['polish-standard:7', 'POLISH_007'],
    canonicalRuleKey: 'polish/tabular-nums',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-tabular-numerics',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.text-wrap-balance',
    sourceRuleAliases: ['polish-standard:8', 'POLISH_008'],
    canonicalRuleKey: 'polish/text-wrap-balance',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'low',
    severity: 'advisory',
    findingClass: 'polish',
    registryScope: 'polished-heading-balance',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.staggered-enter',
    sourceRuleAliases: ['polish-standard:9', 'POLISH_009'],
    canonicalRuleKey: 'polish/staggered-enter',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-enter-stagger',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.subtle-exit',
    sourceRuleAliases: ['polish-standard:10', 'POLISH_010'],
    canonicalRuleKey: 'polish/subtle-exit',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-exit-choreography',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.font-smoothing',
    sourceRuleAliases: ['polish-standard:11', 'POLISH_011'],
    canonicalRuleKey: 'polish/font-smoothing',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'low',
    severity: 'advisory',
    findingClass: 'polish',
    registryScope: 'polished-font-smoothing',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.animatepresence-initial',
    sourceRuleAliases: ['polish-standard:12', 'POLISH_012'],
    canonicalRuleKey: 'polish/animatepresence-initial',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-first-load-suppression',
    evidenceRequirements: ['markup'],
    supportedSourceKinds: supportedKindsFor('markup'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.sparse-will-change',
    sourceRuleAliases: ['polish-standard:13', 'POLISH_013'],
    canonicalRuleKey: 'polish/sparse-will-change',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'low',
    severity: 'advisory',
    findingClass: 'polish',
    registryScope: 'polished-sparse-will-change',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.shadows-over-borders',
    sourceRuleAliases: ['polish-standard:14', 'POLISH_014'],
    canonicalRuleKey: 'polish/shadows-over-borders',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-elevation-shadow',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.optical-alignment',
    sourceRuleAliases: ['polish-standard:15', 'POLISH_015'],
    canonicalRuleKey: 'polish/optical-alignment',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-optical-alignment',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.typography-rhythm',
    sourceRuleAliases: ['polish-standard:16', 'POLISH_016'],
    canonicalRuleKey: 'polish/typography-rhythm',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-vertical-rhythm',
    evidenceRequirements: ['computed-style'],
    supportedSourceKinds: supportedKindsFor('computed-style'),
    scope: 'component',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'inconclusive',
  },
  {
    ruleId: 'polish.shadow-hierarchy',
    sourceRuleAliases: ['polish-standard:17', 'POLISH_017'],
    canonicalRuleKey: 'polish/shadow-hierarchy',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-shadow-hierarchy',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    // SEED (unchanged): id 19, critical -> blocker.
    ruleId: 'polish.reduced-motion-respect',
    sourceRuleAliases: ['polish-standard:19', 'POLISH_019'],
    canonicalRuleKey: 'polish/reduced-motion-respect',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'critical',
    severity: 'blocker',
    findingClass: 'polish',
    registryScope: 'polished-motion-respect',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.state-completeness',
    sourceRuleAliases: ['polish-standard:21', 'POLISH_021'],
    canonicalRuleKey: 'polish/state-completeness',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'high',
    severity: 'major',
    findingClass: 'polish',
    registryScope: 'polished-state-completeness',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'polish.anti-pattern-genericity',
    sourceRuleAliases: ['polish-standard:22', 'POLISH_022'],
    canonicalRuleKey: 'polish/anti-pattern-genericity',
    ownerValidatorId: 'polish-standard',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'medium',
    severity: 'minor',
    findingClass: 'polish',
    registryScope: 'polished-genericity-floor',
    evidenceRequirements: ['dom'],
    supportedSourceKinds: supportedKindsFor('dom'),
    scope: 'component',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'inconclusive',
  },

  // ====================== owner static-a11y (3) ======================
  {
    // SEED: id 18, css-rule blocker (the only required static-a11y rule).
    ruleId: 'a11y.focus-visible',
    sourceRuleAliases: ['polish-standard:18', 'POLISH_018'],
    canonicalRuleKey: 'a11y/focus-visible',
    ownerValidatorId: 'static-a11y',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'critical',
    severity: 'blocker',
    findingClass: 'a11y',
    registryScope: 'keyboard-accessibility-floor',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    // SEED: id 5, dom-only -> owned non-required -> inconclusive until P4b.
    ruleId: 'a11y.min-hit-area',
    sourceRuleAliases: ['polish-standard:5', 'POLISH_005'],
    canonicalRuleKey: 'a11y/min-hit-area',
    ownerValidatorId: 'static-a11y',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'critical',
    severity: 'blocker',
    findingClass: 'a11y',
    registryScope: 'touch-target-floor',
    evidenceRequirements: ['dom'],
    supportedSourceKinds: supportedKindsFor('dom'),
    scope: 'component',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'inconclusive',
  },
  {
    // id 20, contrast-only -> owned non-required -> inconclusive until P4b.
    ruleId: 'a11y.color-contrast',
    sourceRuleAliases: ['polish-standard:20', 'POLISH_020'],
    canonicalRuleKey: 'a11y/color-contrast',
    ownerValidatorId: 'static-a11y',
    sourceVocabulary: 'polish-extended-antipattern',
    sourceSeverity: 'critical',
    severity: 'blocker',
    findingClass: 'a11y',
    registryScope: 'contrast-floor',
    evidenceRequirements: ['contrast'],
    supportedSourceKinds: supportedKindsFor('contrast'),
    scope: 'component',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'inconclusive',
  },

  // ====================== owner theming (2) ======================
  {
    // SEED: taste/hex-in-interactive-state, error -> blocker.
    ruleId: 'theming.hex-in-interactive-state',
    sourceRuleAliases: ['taste/hex-in-interactive-state'],
    canonicalRuleKey: 'theming/token-driven-interactive-state',
    ownerValidatorId: 'theming',
    sourceVocabulary: 'taste',
    sourceSeverity: 'error',
    severity: 'blocker',
    findingClass: 'theming',
    registryScope: 'token-consistency',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'theming.border-radius-consistency',
    sourceRuleAliases: ['taste/border-radius-inconsistency'],
    canonicalRuleKey: 'theming/border-radius-consistency',
    ownerValidatorId: 'theming',
    sourceVocabulary: 'taste',
    sourceSeverity: 'error',
    severity: 'blocker',
    findingClass: 'theming',
    registryScope: 'token-consistency',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },

  // ====================== owner anti-pattern (6) ======================
  {
    // SEED: gradient-text, P1 -> major (precise CSS detector, blocking).
    ruleId: 'anti-pattern.gradient-text',
    sourceRuleAliases: ['gradient-text'],
    canonicalRuleKey: 'anti-pattern/gradient-text',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P1',
    severity: 'major',
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'anti-pattern.glassmorphism-default',
    sourceRuleAliases: ['glassmorphism-default'],
    canonicalRuleKey: 'anti-pattern/glassmorphism-default',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P1',
    severity: 'major',
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'anti-pattern.side-stripe-borders',
    sourceRuleAliases: ['side-stripe-borders'],
    canonicalRuleKey: 'anti-pattern/side-stripe-borders',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P1',
    severity: 'major',
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['css-rule'],
    supportedSourceKinds: supportedKindsFor('css-rule'),
    scope: 'file',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    // SEED: identical-card-grids, P1 default major DEMOTED to minor (heuristic).
    // scope:project - its source scanner reasons over a page/project shape.
    ruleId: 'anti-pattern.identical-card-grids',
    sourceRuleAliases: ['identical-card-grids'],
    canonicalRuleKey: 'anti-pattern/identical-card-grids',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P1',
    severity: 'minor',
    severityOverrideReason: STRUCTURAL_OVERRIDE_REASON,
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['markup'],
    supportedSourceKinds: supportedKindsFor('markup'),
    scope: 'project',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    ruleId: 'anti-pattern.hero-metric-template',
    sourceRuleAliases: ['hero-metric-template'],
    canonicalRuleKey: 'anti-pattern/hero-metric-template',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P1',
    severity: 'minor',
    severityOverrideReason: STRUCTURAL_OVERRIDE_REASON,
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['markup'],
    supportedSourceKinds: supportedKindsFor('markup'),
    scope: 'project',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
  {
    // P2 -> minor (table default; heuristic but no override needed).
    ruleId: 'anti-pattern.modal-as-first-thought',
    sourceRuleAliases: ['modal-as-first-thought'],
    canonicalRuleKey: 'anti-pattern/modal-as-first-thought',
    ownerValidatorId: 'anti-pattern',
    sourceVocabulary: 'p012',
    sourceSeverity: 'P2',
    severity: 'minor',
    findingClass: 'anti-pattern',
    registryScope: 'named-ban-compliance',
    evidenceRequirements: ['markup'],
    supportedSourceKinds: supportedKindsFor('markup'),
    scope: 'project',
    narrowTargetBehavior: 'evaluate_expanded_context',
    applicability: 'not_applicable',
  },
];

export function getRule(canonicalRuleKey: string): ProductRuleDefinition | null {
  return RULES.find((r) => r.canonicalRuleKey === canonicalRuleKey) ?? null;
}
export function getRuleById(ruleId: string): ProductRuleDefinition | null {
  return RULES.find((r) => r.ruleId === ruleId) ?? null;
}
export function resolveSourceAlias(sourceId: string): ProductRuleDefinition | null {
  return RULES.find((r) => r.sourceRuleAliases.includes(sourceId)) ?? null;
}
