// GENERATED by sidecoach/scripts/generate-validators.ts - DO NOT EDIT BY HAND.
// Source: product-rule-registry.ts + flow-validation-capabilities.ts
import type { CleanPolicy, SourceKindSupport } from './product-rule-types';

export interface GeneratedValidator { validatorId: string; ownedRuleIds: string[]; registryScope: string[]; supportedSourceKinds: SourceKindSupport[]; cleanPolicy: CleanPolicy; }
export interface GeneratedFlowCapability { flowId: string; capability: 'product_validator' | 'advisory' | 'none'; }

export const GENERATED_VALIDATORS: GeneratedValidator[] = [
  {
    "validatorId": "polish-standard",
    "ownedRuleIds": [
      "polish.reduced-motion-respect"
    ],
    "registryScope": [
      "polished-motion-respect"
    ],
    "supportedSourceKinds": [
      {
        "kind": "css",
        "level": "full"
      },
      {
        "kind": "html",
        "level": "partial"
      },
      {
        "kind": "less",
        "level": "full"
      },
      {
        "kind": "scss",
        "level": "full"
      },
      {
        "kind": "tsx",
        "level": "partial"
      }
    ],
    "cleanPolicy": {
      "requiredRuleIds": [
        "polish.reduced-motion-respect"
      ],
      "blockingSeverities": [
        "blocker",
        "major"
      ],
      "toleratedFindingCounts": {
        "blocker|polish": 0
      },
      "requiredCoverageByScope": [
        {
          "ruleId": "polish.reduced-motion-respect",
          "scope": "file",
          "evidenceAlternativesByRequirement": [
            [
              "css",
              "scss",
              "less",
              "tsx",
              "html"
            ]
          ],
          "requireAllDiscoveredApplicableFiles": true
        }
      ],
      "inconclusiveBehavior": "block",
      "notApplicableBehavior": "exclude_and_report"
    }
  },
  {
    "validatorId": "theming",
    "ownedRuleIds": [
      "theming.hex-in-interactive-state"
    ],
    "registryScope": [
      "token-consistency"
    ],
    "supportedSourceKinds": [
      {
        "kind": "css",
        "level": "full"
      },
      {
        "kind": "html",
        "level": "partial"
      },
      {
        "kind": "less",
        "level": "full"
      },
      {
        "kind": "scss",
        "level": "full"
      },
      {
        "kind": "tsx",
        "level": "partial"
      }
    ],
    "cleanPolicy": {
      "requiredRuleIds": [
        "theming.hex-in-interactive-state"
      ],
      "blockingSeverities": [
        "blocker",
        "major"
      ],
      "toleratedFindingCounts": {
        "blocker|theming": 0
      },
      "requiredCoverageByScope": [
        {
          "ruleId": "theming.hex-in-interactive-state",
          "scope": "file",
          "evidenceAlternativesByRequirement": [
            [
              "css",
              "scss",
              "less",
              "tsx",
              "html"
            ]
          ],
          "requireAllDiscoveredApplicableFiles": true
        }
      ],
      "inconclusiveBehavior": "block",
      "notApplicableBehavior": "exclude_and_report"
    }
  },
  {
    "validatorId": "anti-pattern",
    "ownedRuleIds": [
      "anti-pattern.gradient-text",
      "anti-pattern.identical-card-grids"
    ],
    "registryScope": [
      "named-ban-compliance"
    ],
    "supportedSourceKinds": [
      {
        "kind": "css",
        "level": "full"
      },
      {
        "kind": "html",
        "level": "full"
      },
      {
        "kind": "jsx",
        "level": "partial"
      },
      {
        "kind": "less",
        "level": "full"
      },
      {
        "kind": "scss",
        "level": "full"
      },
      {
        "kind": "svelte",
        "level": "partial"
      },
      {
        "kind": "tsx",
        "level": "partial"
      },
      {
        "kind": "vue",
        "level": "partial"
      }
    ],
    "cleanPolicy": {
      "requiredRuleIds": [
        "anti-pattern.gradient-text",
        "anti-pattern.identical-card-grids"
      ],
      "blockingSeverities": [
        "blocker",
        "major"
      ],
      "toleratedFindingCounts": {
        "major|anti-pattern": 0
      },
      "requiredCoverageByScope": [
        {
          "ruleId": "anti-pattern.gradient-text",
          "scope": "file",
          "evidenceAlternativesByRequirement": [
            [
              "css",
              "scss",
              "less",
              "html"
            ]
          ],
          "requireAllDiscoveredApplicableFiles": true
        },
        {
          "ruleId": "anti-pattern.identical-card-grids",
          "scope": "page",
          "evidenceAlternativesByRequirement": [
            [
              "html",
              "tsx",
              "jsx",
              "vue",
              "svelte"
            ]
          ],
          "requireAllDiscoveredApplicableFiles": true
        }
      ],
      "inconclusiveBehavior": "block",
      "notApplicableBehavior": "exclude_and_report"
    }
  },
  {
    "validatorId": "static-a11y",
    "ownedRuleIds": [
      "a11y.focus-visible",
      "a11y.min-hit-area"
    ],
    "registryScope": [
      "keyboard-accessibility-floor",
      "touch-target-floor"
    ],
    "supportedSourceKinds": [
      {
        "kind": "css",
        "level": "full"
      },
      {
        "kind": "dom",
        "level": "full"
      },
      {
        "kind": "html",
        "level": "partial"
      },
      {
        "kind": "less",
        "level": "full"
      },
      {
        "kind": "scss",
        "level": "full"
      },
      {
        "kind": "tsx",
        "level": "partial"
      }
    ],
    "cleanPolicy": {
      "requiredRuleIds": [
        "a11y.focus-visible"
      ],
      "blockingSeverities": [
        "blocker",
        "major"
      ],
      "toleratedFindingCounts": {
        "blocker|a11y": 0
      },
      "requiredCoverageByScope": [
        {
          "ruleId": "a11y.focus-visible",
          "scope": "file",
          "evidenceAlternativesByRequirement": [
            [
              "css",
              "scss",
              "less",
              "tsx",
              "html"
            ]
          ],
          "requireAllDiscoveredApplicableFiles": true
        }
      ],
      "inconclusiveBehavior": "block",
      "notApplicableBehavior": "exclude_and_report"
    }
  }
];

export const GENERATED_FLOW_CAPABILITIES: GeneratedFlowCapability[] = [
  {
    "flowId": "flowJ_tactical_polish",
    "capability": "product_validator"
  },
  {
    "flowId": "flowM_responsive_validation",
    "capability": "advisory"
  },
  {
    "flowId": "flowK_multi_lens_audit",
    "capability": "advisory"
  },
  {
    "flowId": "flowI_accessibility",
    "capability": "advisory"
  },
  {
    "flowId": "flowL_design_critique",
    "capability": "advisory"
  },
  {
    "flowId": "flowA_brand_verify",
    "capability": "none"
  }
];
