#!/bin/bash
# One-time setup: trust the endow WS server's self-signed cert in the macOS
# System Keychain. After this runs successfully, Safari and Chrome will load
# https://localhost:9224/endow-core.js silently with no "untrusted" warning.
#
# The cert itself is auto-generated by ws-server on first start. Run this
# AFTER restarting Claude Code (or the endow MCP server) so the cert exists.

set -euo pipefail

CERT_PATH="${HOME}/.claude/endow/dist/server/certs/cert.pem"

if [ ! -f "$CERT_PATH" ]; then
  echo "ERROR: cert not found at $CERT_PATH"
  echo ""
  echo "The endow MCP server auto-generates this on first start. You need to:"
  echo "  1. Quit and relaunch Claude Code (so the endow MCP server starts fresh"
  echo "     with the HTTPS code that generates the cert)."
  echo "  2. After Claude Code is back up, run this script again."
  exit 1
fi

echo "Trusting cert at $CERT_PATH in macOS System Keychain."
echo "You'll be prompted for your admin password ONCE."
echo ""

sudo security add-trusted-cert -d -r trustRoot \
  -k /Library/Keychains/System.keychain \
  "$CERT_PATH"

echo ""
echo "Done. Safari and Chrome now trust the endow HTTPS endpoint."
echo "Reload your dev page once - the endow toolbar should appear with no"
echo "cert warning and no mixed-content block."
